fleaflet/flutter_map

flutter_map/lib/src/map/map.dart
=> Fixed marker redraw on map rotation.

lib/flutter_map.dart
I add @required before options because if there is no option the map crash.
=> option is required

example/lib/main.dart, example/lib/pages/on_tap.dart, example/lib/widgets/drawer.dart
Added a new example page for marker ontap.
Fixes https://github.com/apptreesoftware/flutter_map/issues/102.
=> Added onTap example

lib/src/layer/tile_layer.dart, pubspec.yaml
=> Added NetworkImageWithRetry to TileLayer

lib/flutter_map.dart, lib/src/layer/circle_layer.dart, lib/src/map/flutter_map_state.dart
Added a new layer type, drawing circles at coordinates.
=> Added circle layer

lib/flutter_map.dart, lib/src/gestures/gestures.dart, lib/src/map/map.dart
Added hasGesture property on MapPosition. OnPositionChanged user can check if map is moved by controller or by user gestures.
=> to close #138 detect if map move depends on gestures

lib/src/gestures/gestures.dart, lib/src/gestures/latlng_tween.dart, lib/src/map/flutter_map_state.dart, pubspec.yaml
It uses [GestureDetector wrapper package](https://pub.dartlang.org/packages/positioned_tap_detector) as a dependency that I wrote to achieve this behavior.
=> Zoom to focal point on double tap and scale gestures

example/lib/pages/marker_anchor.dart, lib/src/layer/marker_layer.dart
=> Make anchor field public

example/lib/pages/animated_map_controller.dart, example/lib/pages/map_controller.dart, lib/flutter_map.dart, lib/src/map/map.dart
#113 
Asymetric padding has many use cases. EdgeInsets is idiomatic flutter way to provide this. The existing code was pretty much ready, I really only changed types
=> FitBoundsOptions EdgeInsets padding

lib/flutter_map.dart, lib/src/layer/circle_layer.dart, lib/src/layer/group_layer.dart, lib/src/map/flutter_map_state.dart
=>  Add GroupLayer

lib/src/layer/circle_layer.dart, lib/src/map/flutter_map_state.dart
=>  Add rebuild stream to CircleLayer

lib/src/layer/tile_layer.dart
Support for tile requests from tms server.
=> conversion 'y' coord's to tms request

pubspec.yaml
The main update here is cached_network_image.
Fixes #234, #263
=> Updates dependencies

example/lib/pages/animated_map_controller.dart
=> Increase maxZoom to 10.0 in AnimatedMapControllerPage sample

example/.gitignore, example/ios/.gitignore
Ignore files generated when running example on iOS.
=> Update .gitignore for the example

pubspec.yaml
- Updated most of dependencies under the `pubspec.yaml` file.
- Updated Dart SDK version to `2.2.2`.
=> Updated dependencies

README.md
Hi, i created plugin flutter_map_marker_cluster.
I think that it will be usefull for many people, so i would add reference.
=> Add plugin reference flutter_map_marker_cluster in readme

example/lib/pages/circle.dart, lib/src/layer/circle_layer.dart
I linked the parameters for the border. #297
=> add border circle

analysis_options.yaml, lib/flutter_map.dart, lib/src/layer/mbtiles/mbtiles_image_provider.dart, lib/src/layer/tile_layer.dart
=> Dart Analysis solve and exclude example

lib/src/layer/polygon_layer.dart
As title i closed the polygon adding  last border line in Polygon.
=> Added last border line in Polygon to close when borderStrokeWidth > 0

lib/src/layer/circle_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart
Fix for this issue:
https://github.com/johnpryan/flutter_map/issues/311
=> Fix for type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'

pubspec.yaml
=> update cached_network_image, path_provider and test

lib/src/layer/overlay_image_layer.dart
The previous implementation of OverlayImageLayer was not correct because the image loading was not awaited which led to an exeption on the first frame.
Thanks to @slightfoot we could streamline the whole file.
I hope you like it.
=> streamlined and bugfix of OverlayImageLayer 

lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
=> update MapState options when the FlutterMap widget's options change

lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
=> Fix Unsupported Operation and add missing onTap and onLongPress methods 

lib/src/layer/tile_layer.dart
An option for controlling a tile layers opacity
=> add opacity option to tile layers

lib/src/layer/polygon_layer.dart
Hello, I made some changes to support holed polygons.
You can border holes too:
Support dotted borders:
Or you can disable hole borders:
Closes #484
=> Support holed polygon

README.md
=> Remove mapbox from README

lib/src/layer/tile_layer.dart
"binded" is an incorrect conjugation of "bind". "bound" is the correct conjugation.
=> binded -> bound

example/lib/pages/zoombuttons_plugin_option.dart
Zoom buttons are nice, I needed colors & icons changes, so I added it as example options! 🍺
=> Add icons & color params for zoombuttons

lib/src/layer/polyline_layer.dart
This fixes Polylines failing to render on web, as described in #446 with --dart-define=FLUTTER_WEB_USE_SKIA=false.
The true root cause is that canvas.saveLayer does not work, see [flutter issue #48417](https://github.com/flutter/flutter/issues/48417). This works around that problem by using different blend modes, which works in most cases, but it is not a perfect fix. Overlapping translucent polylines with borders render incorrectly at the point of overlap. This seems rare enough to me.
On platforms where canvas.saveLayer does work, the fix has no effect. So overlapping translucent polylines with borders will continue to work correctly (tested with Android).
While I was in there, I fixed the border size for dotted lines and changed them to use paths. Large border sizes can cause the dots …
=> Fix #446: Polyline rendering on web

README.md
Added a missing required comma in line 165 and added a trailing comma for consistency in line 203.
=> Fixed syntax in README.md

README.md
Stay consistent with other examples in this document as well with official docs.
=> Remove unnecessary "new" tokens

lib/src/geo/crs/crs.dart
=> use _inclusive() in inclusiveLng()

README.md
lol it's funny there is a single comma missing and copy paste gives error.
=> added a single comma (,) :3

.github/workflows/stale.yml
re: https://github.com/fleaflet/flutter_map/discussions/848
=> Add actions/stale@v3 GitHub Action

example/lib/main.dart, example/lib/pages/marker_rotate.dart, example/lib/widgets/drawer.dart, lib/src/layer/marker_layer.dart
This PR fixes https://github.com/fleaflet/flutter_map/issues/863
=> Added marker option to counter rotated markers to the map rotation

lib/flutter_map.dart, lib/src/map/flutter_map_state.dart
This fixes #867 by adding an onMapCreated callback to the map options.
=> Added onMapCreated callback

lib/flutter_map.dart, lib/src/geo/latlng_bounds.dart
In some cases it might be useful to know whether e.g. LatLngBound *are* just some other LatLngBounds.
I created a proper operator implementation making it easyer to determine and making all user's implementations cleaner.
=> Implemented equality operators for LatLngBounds and MapPosition

example/lib/pages/custom_crs/custom_crs.dart, example/lib/pages/scale_layer_plugin_option.dart, example/lib/pages/zoombuttons_plugin_option.dart, lib/flutter_map.dart, lib/src/gestures/gestures.dart, lib/src/layer/circle_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
Removed unnecessary imports (flagged by `dart analyze`) to fix automated checks. Nothing else changed.
=> Fix automated checks

lib/src/layer/polyline_layer.dart
This just adds two options to the Polyline that otherwise require a plugin and copying most of the polyline rendering code.
=> Add stroke cap and join options to Polyline

pubspec.yaml
Update dependency to consume fix for
arsamme/flutter-positioned-tap-detector/issues/1
=> update positioned_tap_detector_2 dependency

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/general.md, .github/ISSUE_TEMPLATE/question-help.md
Follow up for maintenance work I've been doing using labels. An attempt to improve organization on this project, as mentioned in https://github.com/fleaflet/flutter_map/discussions/1117.
If you want to see how it is to use, feel free to create issues over at my fork: https://github.com/JaffaKetchup/flutter_map.
=> Create Issue Templates

README.md
2 plugins flutter_map_line_editor and flutter_map_dragmarker now in pub.dev to add to readme.
=> added flutter_map_line_editor and flutter_map_dragmarker plugins

README.md
Package for interpolating using Haversine formula along LatLng (or other points) for gradual line drawing or moving markers along a path.
=> Added line_animator plugin/package

CHANGELOG.md, README.md
- Updated CHANGELOG
- Fixed CHANGELOG and README markdown linting problems
=> Prepare For Release

CHANGELOG.md, pubspec.yaml
- Changed pubspec.yaml package version
- Updated CHANGELOG.md
Waiting on #1319 and #1325 before a release can be made, as those will be part of v2.2.0.
=> Prepared For v2.2.0 Release

example/lib/pages/animated_map_controller.dart, example/lib/pages/circle.dart, example/lib/pages/home.dart, example/lib/pages/interactive_test_page.dart, example/lib/pages/latlng_to_screen_point.dart, example/lib/pages/live_location.dart, example/lib/pages/many_markers.dart, example/lib/pages/map_controller.dart, example/lib/pages/map_inside_listview.dart, example/lib/pages/marker_anchor.dart, example/lib/pages/marker_rotate.dart, example/lib/pages/max_bounds.dart, example/lib/pages/moving_markers.dart, example/lib/pages/network_tile_provider.dart, example/lib/pages/on_tap.dart, example/lib/pages/overlay_image.dart, example/lib/pages/plugin_scalebar.dart, example/lib/pages/plugin_zoombuttons.dart, example/lib/pages/point_to_latlng.dart, example/lib/pages/polygon.dart, example/lib/pages/polyline.dart, example/lib/pages/reset_tile_layer.dart, example/lib/pages/stateful_markers.dart, example/lib/pages/tile_builder_example.dart, example/lib/pages/tile_loading_error_handle.dart, example/lib/pages/widgets.dart, example/lib/test_app.dart, lib/src/core/util.dart, test/flutter_map_test.dart
https://github.com/openstreetmap/operations/issues/737
Signed-off-by: Grant Slater <git@firefishy.com>
=> Use preferred tile.openstreetmap.org URL

lib/src/layer/marker_layer.dart
=> Stateless Marker Layer

example/lib/pages/reset_tile_layer.dart, lib/flutter_map.dart, lib/src/layer/tile_layer/tile_provider/network_image_provider.dart
Fixes https://github.com/fleaflet/flutter_map/issues/1360.
=> Fix Reset TileLayer example

lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart
In order to use the RepaintBoundary the each vector is broken up into two: a support vector (Positioned) and a local vector (map.project), so that the local projection can be repositioned w/o always requiring a full redraw. However, as it turns out, the implementation has not enough precision to correctly position vectors very close to each other (it's likely due to map projection and/or integer precision). This is particularly noticeable when e.g. drawing a dotted line (which is just a bunch of close by polygons) or a polygon with a boundary (which is just a polygon and a polyline precisely layered atop each other).
=> Revert RepaintBoundary optimization due to visual artifacting.

usage/basics.md
Updated material_floating_search_bar to the new url, since the old one is deleted/discontinued
=> Linking to new package

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yaml, CONTRIBUTING.md, pubspec.yaml
* Updated issue templates
* Bumped project version
* Added CONTRIBUTING.md (based off the online docs version)
=> Repository (meta) Improvements

example/android/app/build.gradle, example/android/app/src/debug/AndroidManifest.xml, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/profile/AndroidManifest.xml, example/android/build.gradle
Bumped Android Gradle Plugin 7.1.3 to 7.4.2. Also moved package from Android manifest to build files (per current recommendations).
Following the [Guided fix using Android Studio](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide)
=> Upgraded Gradle version for Android demo app

lib/src/layer/tile_layer/tile_layer.dart
=> Avoid setting 'User-Agent' header in `TileProvider` when on web platform

example/lib/plugins/zoombuttons_plugin.dart
Removed some bounding controls so that zooms get increased / decreased by 1.
=> fix(example): ensure zoom buttons zoom by a full zoom level only

.github/workflows/branch.yml, .github/workflows/master.yml, .github/workflows/publish.yml
This makes releases a little easier. Also improves build integrity.
=> chore(meta): added automatic publishing of package to pub.dev on tag creation
