fleaflet/flutter_map

flutter_map/lib/src/layer/tile_layer.dart, flutter_map_example/lib/main.dart
This is a test branch that enables CORS support.  I still need to do some testing to see if this improves performance for various map providers
to use, you can put the {s} tag in your URL template and supply the subdomains:
```dart
layers: [
new TileLayerOptions(
urlTemplate:
"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
subdomains: ['a','b','c']
),
new MarkerLayerOptions(markers: markers)
],
```
FYI @wmleler
=> add subdomain support

flutter_map/lib/flutter_map.dart, flutter_map/lib/src/layer/polyline_layer.dart
=> Add Polyline

README.md
So people can find other map tile providers
=> link to other tile providers

flutter_map/lib/src/layer/marker_layer.dart
=> Add marker anchor support

flutter_map/lib/src/layer/tile_layer.dart, flutter_map/pubspec.yaml
This fixes continuous exceptions caused by the previous default MemoryImage being initialized with `new Uint8List(0)`
```
I/flutter (10904): Another exception was thrown: Exception: operation failed
E/flutter (10904): [ERROR:flutter/lib/ui/painting/codec.cc(83)] InitCodec failed - buffer was empty
I/chatty  (10904): uid=10093(net.nbspou.infapp) 1.io identical 17 lines
E/flutter (10904): [ERROR:flutter/lib/ui/painting/codec.cc(83)] InitCodec failed - buffer was empty
I/flutter (10904): Another exception was thrown: Exception: operation failed
```
=> Allow custom placeholder image and use transparent_image for default

flutter_map/lib/src/gestures/gestures.dart
As per [Issue #42](https://github.com/apptreesoftware/flutter_map/issues/42), I have applied a min max constraint check on zoom within handleScaleUpdate in gestures.dart.
=> Applied constraints to zoom on gesture update if min or max options set

flutter_map/lib/flutter_map.dart, flutter_map/lib/src/map/map.dart
MapOptions now has 2 new variables, swPanBoundary and nwPanBoundary. Immediate assert fail if center variable is outside pan boundary. map.dart's move() function returns out if *new center is out of pan bounds.
=> Pan Boundary with 2 new MapOptions variables: swPanBoundary and nePanBoundary.

flutter_map/lib/src/layer/tile_layer.dart
Resolves [issue 3](https://github.com/apptreesoftware/flutter_map/issues/3).
Added OfflineMode bool variable to TileLayerOptions, if true, image uses AssetImage(), if false (default) image uses NetworkImage(). 
Note: Only the newest (7th jun 2018) master build of flutter enables pubspec to look in asset directories, else pubspec will require direct paths to all map asset images. 
To get offline maps tiles, see here: [mbtilesToPngs](https://github.com/alfanhui/mbtilesToPngs)
=> OfflineMode bool variable added to TileLayerOptions for AssetImage Widget use

flutter_map/lib/src/gestures/gestures.dart, flutter_map/lib/src/map/flutter_map_state.dart
Added the necessary code to support double-tap to zoom. Also added a dispose function. Note that it zooms in the center, not where the user tapped. See https://github.com/flutter/flutter/issues/10048.
Closes https://github.com/apptreesoftware/flutter_map/issues/73
=> Add double-tap to zoom

flutter_map/pubspec.yaml
After upgrading to flutter 0.5.8-pre.155 I'm getting an error on missing math.PI (which was obsolete)
flutter version:
```bash
Flutter 0.5.8-pre.155 • channel master • https://github.com/flutter/flutter.git
Framework • revision 78a00cb13a (6 days ago) • 2018-08-01 22:56:49 -0700
Engine • revision a61fae0824
Tools • Dart 2.0.0-dev.69.3.flutter-937ee2e8ca
```
And the error:
```bash
compiler message: file:///Users/aroba/flutter/.pub-cache/hosted/pub.dartlang.org/latlong-0.4.5/lib/latlong.dart:74:53: Error: Getter not found: 'PI'.
compiler message: double degToRadian(final double deg) => deg * (math.PI / 180.0);
compiler message:                                                     ^^
compiler message: file:///Users/aroba/flutter/.pub-cache/hosted/pub.dartlang.org/latlong-0.4.5/lib/latlong.dart …
```
=> Upgrade latlong version from 0.4.0 to 0.5.3

example/lib/pages/map_controller.dart, lib/flutter_map.dart, lib/src/layer/marker_layer.dart, lib/src/map/map.dart
Provides a way for clients to get the current map bounds.
Fixes #87 
- Calculates the map bounds on `move`.
- Caches the value in `MapState` and exposes a `bounds` getter.
- Adds `bounds` property to `MapPosition`, and provides it upon triggering the `onPositionChanged` callback.
- Adds `bounds` getter to `MapController`/`MapControllerImpl`.
- Updates the MapController example with a button that shows the current bounds in a `SnackBar`.
=> Expose map bounds

lib/src/layer/polyline_layer.dart
I've added some polyline customisations like a border and the option to draw it as a dotted line:
=> Added polyline customisation options

README.md
The pubspec example in the README is badly out of date in its version number, which isn't good as people will tend to copy and paste that line as-is into their pubspecs.
=> Update the version number in the README

example/lib/pages/plugin_api.dart, lib/src/layer/layer.dart, lib/src/layer/marker_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer.dart, lib/src/map/flutter_map_state.dart, lib/src/plugins/plugin.dart, pubspec.yaml
Added rebuild capability using official package `package:async/async.dart` and `StreamGroup` to merge user-specified rebuild stream in `LayerOptions` with `onMoved` stream in `MapState`. Each time a new item is added to either stream, the `StreamBuilder` in each layer widget rebuilds the layer. 
**Details**
A new `StreamGroup` is created for each new layer created in the build method of `FlutterMapState`. `StreamGroup` instances created during last build are discarded before new `StreamGroups` are created and when the `StatefulWidget` implementing each layer is disposed, ensuring proper release of stream resources. 
Close #142.
=> Added rebuild capabiltiy to LayerOptions

lib/src/map/flutter_map_state.dart
Fixes the issue where all layers get rebuilt, whenever only one of them change its bounds https://github.com/apptreesoftware/flutter_map/issues/130.
=> Prevent map layers excessive builds

lib/src/core/bounds.dart, lib/src/core/point.dart, lib/src/geo/crs/crs.dart, lib/src/gestures/gestures.dart, lib/src/layer/tile_layer.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
Rename the class Point to Custompoint so it doesnt interfere with the dart:math Point class. Fixes #185.
=> Rename Point class

lib/flutter_map.dart
I did a mistake with this property so probably will be better if we will remove this. 
https://github.com/johnpryan/flutter_map/issues/33
=> Remove layers property from MapOptions #33

lib/src/layer/tile_layer.dart, pubspec.yaml
#203 
Add option( `cachedTiles=true` ) for use CachedNetworkImageProvider instead NetworkImageWithRetry.
Storage image tiles in cache memory, for keep the images tiles after restart the application even if there is no internet connection.
=> adding cached network image dependency for tiles

lib/src/map/flutter_map_state.dart
Hi 😊
This will close issue #20. Note that this way also the tap detectors will not be called. Is this the expected behaviour? Maybe the meaning of the `interactive` option should be clarified.
=> Use PositionedTapDetector only when in interactive mode

example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/lib/main.dart, example/lib/pages/circle.dart, example/lib/pages/overlay_image.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/layer/circle_layer.dart, lib/src/layer/group_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/map/flutter_map_state.dart
CircleMarker example:
```dart
new CircleMarker(
point: new LatLng(51.5, -0.09),
color: Colors.blue.withOpacity(0.7),
useRadiusInMeter: true,
radius: 2000// 2000 meters | 2 km
)
```
Overlay image example:
```dart
new OverlayImage(
bounds: LatLngBounds(LatLng(51.5, -0.09),LatLng(48.8566, 2.3522)),
opacity: 0.8,
imageProvider: NetworkImage('https://images.pexels.com/photos/231009/pexels-photo-231009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=300&w=600')
)
```
All modifications with full examples
=> CircleMarker radius in meters and  new overlay image layer

example/android/gradle/wrapper/gradle-wrapper.properties
Executing `flutter run` in the example folder, with a running Pixel API 28 emulator, causes the following error:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
> Minimum supported Gradle version is 4.6. Current version is 3.3. If using the gradle wrapper, try editing the distributionUrl in
flutter_map/example/android/gradle/wrapper/gradle-wrapper.properties to gradle-4.6-all.zip
```
Updated the distributionUrl to gradle-4.6-all.zip
It is possible to run the example app in the Android emulator.
=> Update gradle wrapper

README.md
Executing `flutter run` in the example folder, with a running iPhone XR simulator, causes the following error:
```
Launching lib/main.dart on iPhone XR in debug mode...
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
```
From the log, I can read:
```
FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files, errno = 24)
```
Which is the problem reported here: https://github.com/trentpiercy/trace/issues/1
Updated the README with the instructions I found in the link.
It is possible to run the example app in the iOS simulator.
=> Updated README to run the example.

lib/flutter_map.dart
This happens if you zoom out & pan too much. I am not sure if this should be fixed somewhere else so that center is never null but this is a quick fix for this particular place.
```
I/flutter (10829): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (10829): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter (10829): The getter 'latitude' was called on null.
I/flutter (10829): Receiver: null
I/flutter (10829): Tried calling: latitude
I/flutter (10829): 
I/flutter (10829): When the exception was thrown, this was the stack:
I/flutter (10829): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (10829): #1      MapOptions.isOutOfBounds …
```
=> Fixes null pointer in isOutOfBounds

lib/src/geo/latlng_bounds.dart
It is unnecessary to both expose the variables (`sw` and `ne`) and have separate getters (`southWest` and `northEast`) for them. It might even be confusing since someone might wonder what the difference between them is. Therefore I suggest that we make the variables sw and ne private.
=> make sw and ne private

example/lib/pages/esri.dart
The esri page used the add pins page route name. This resulted in the add pins route being marked as active in the drawer.
=> fix(EsriPage): drawer route string

lib/src/layer/polygon_layer.dart
This commit adds the option to make polygons dotted by setting the isDotted argument to true like it is currently possible when adding a polyline. The specific code has been copy/pasted from the polyline widget with a few adjustments.
=> Add isDotted argument to polygon

lib/src/core/bounds.dart, lib/src/layer/marker_layer.dart, lib/src/map/map.dart
When the anchor point is out of bounds, the whole marker widget disappears
=> #230 issue fix

lib/flutter_map.dart, lib/src/layer/marker_layer.dart, lib/src/map/map.dart
Hi,
i'm creating a marker cluster plugin with all feature like animation and spiderfy, and this two edits can help me for don't rewrite you code.
=> expose centerzoom, public getBoundsCenterZoom and Anchor.forPos

example/lib/pages/overlay_image.dart
Minor cosmetic update:
I noticed the the Appbar title on the Overlay Image page was 'Circle' and updated it to 'Overlay Image' so it matches its title in the Drawer widget.  
Thanks for the awesome Repo!
=> Changed Example Overlay Image Appbar title to match Drawer title

example/lib/pages/map_controller.dart, lib/flutter_map.dart, lib/src/gestures/gestures.dart, lib/src/layer/tile_layer.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
Hi, 
I added rotation functionality to the map.
Not exactly like asked in https://github.com/johnpryan/flutter_map/issues/116
Because I don't see a lot of benefit of enabling the user to rotate the map but to rotate the map from the app side e.g. connected to the compass.
So the mapController got a rotate function and the map option an initial rotation.
The rotation is done at the outmost scope so I rotate the whole map with all it's layer because it don't make sense for a single layer not to rotate.
I did not change the version, I let that to you when publishing :-)
I hope you like it.
=> rotation added

lib/src/map/map.dart
Hi,
I observed that when you have enabled 'break on all exceptions' that flutter_map threw an exception while initializing due to that `_lastCenter` was not initialized. I changed a little bit the sequence and made sure that in this case `move`  is executed which initializes `_lastCenter` correctly.
IMHO it would be worth to have a closer look over the whole initialization process sometimes.
=> fixed exception during initialization

lib/src/geo/crs/crs.dart
I'have a tablet and when i put FlutterMap with zoom: 1 and minzoom: 1, debug catch a throw in LatLng class because latitude or longitude are invalid ( lat < -90 or > 90 or lng < -180 or > 180). So i inserted a control before, when i unproject the point in pixel. With this fix it doesn't give error when i drag the map outside to the screen.
=> Fix error when unproject bottomLeft or topRight  and lat are < -90 or > 90 or lng are < -180 or > 180

.idea/libraries/Dart_Packages.xml, example/lib/main.dart, example/lib/pages/wms_tile_layer.dart, example/lib/widgets/drawer.dart, flutter_map.iml, lib/src/geo/crs/crs.dart, lib/src/layer/tile_layer.dart, lib/src/layer/tile_provider/tile_provider.dart
Hello, this PR allow to use tile services that working on [WMS](https://en.wikipedia.org/wiki/Web_Map_Service) protocol. The WMS mode activated by adding `WMSTileLayerOptions` to `TileLayerOptions`, like so:
```
TileLayerOptions(
wmsOptions: WMSTileLayerOptions(
baseUrl: 'http://maps.heigit.org/osm-wms/service?',
layers: ['europe_wms:hs_srtm_europa'],
)
)
```
If `wmsOptions` is not set, for building tiles urls applied standard logic.
URL building logic was applied from original [Leaflet/TileLayer.WMS.js](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.WMS.js).
Also PR contains new example page, and add `Epsg4326` crs object.
closes #412
closes #225
=> Wms support.

.gitattributes, example/lib/main.dart, example/lib/pages/custom_crs.dart, example/lib/widgets/drawer.dart, lib/src/geo/crs/crs.dart, pubspec.yaml
Hello guys, me and @fegyi001 made avaible to use custom CRS in this project with help of [proj4dart](https://pub.dev/packages/proj4dart) project (we are the authors of it).
`Proj4Crs` and `Proj4Projection` classes based on [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet) project and it has [BSD 2-Clause "Simplified" License](https://github.com/kartena/Proj4Leaflet/blob/master/LICENSE) so we need to make sure we can use their codebase.
We also added some support for multiple origins based on this [commit](https://github.com/kartena/Proj4Leaflet/pull/171) (which is still not reviewed but I tested this feature on this map and the map isn't bouncing unlike in Leaflet's map 👌).
We made an example page which uses [EPSG:3413](http://epsg.io/3413) crs.
Closes #514
=> Support custom CRS

lib/src/core/util.dart, lib/src/gestures/gestures.dart, lib/src/layer/tile_layer.dart, lib/src/layer/tile_provider/tile_provider.dart, lib/src/map/map.dart, pubspec.yaml
Hello, I made some changes mainly in [tile_layer.dart](/johnpryan/flutter_map/blob/master/lib/src/layer/tile_layer.dart) in order to keep the old tiles on the screen when zooming if new ones not avaible. These changes based on current Leaflet's tile fetching /retaining strategy see [TileLayer.js](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js) / [GridLayer.js](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js).
I also added some missing features like minZoom / minNativeZoom / maxNativeZoom / zoomReverse / zoomOffset / errorImage and fixed / tracked down some other problems which I will mention in closes section.
Normal use case (fast internet connection)
Simulating slow internet connection
Add support for Error tiles
Add support for …
=> Improve tile management

lib/src/layer/overlay_image_layer.dart
Adding an option for setting the `gaplessPlayback` argument on `OverlayImage`'s `Image` widget allows animated overlays to render smoothly.
Note the flickering behaviour in the "before" example that doesn't occur in the "after" example.
=> Add an option for gapless playback on an OverlayImage

lib/src/map/flutter_map_state.dart
This simply moves the plugin check to the top of the layer check. This allows a different version of a layer to be used as a plugin, as it feels if you are including a plugin, it should take priority of selection.
=> Move plugins to front of checks, so they can override defaults

lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart
Added Polyline culling based on screen bounds. (This PR is the polyline version of #449)
If you set `polylineCulling` to `true` on `PolylineLayerOptions` then any polylines outside of the screen’s bounds won't be drawn, therefore, saving rendering time and improving performance when displaying a large set of polylines.
I also updated `PolygonLayerOptions` to calculate boundingBox only when necessary.
closes #610
=> Polyline culling

example/android/app/build.gradle, example/android/app/src/main/AndroidManifest.xml, example/android/build.gradle, example/android/gradle.properties, example/lib/main.dart, example/lib/pages/live_location.dart, example/lib/widgets/drawer.dart, example/pubspec.yaml
#290  Add example page that use [flutterlocation](https://pub.dev/packages/location) to achieve device's location and update it in live. 
* I need a confirm that upgrading sample app's requirements is okay or not. Because I had really hard time with debugging "location" library and finally got a reason why it was not running okay with flutter_map sample app.
https://pub.dev/packages/location#breaking-changes
as described on README page, location version 2 uses AndroidX and SDK 28 to run it. 
If you guys think it's too unnecessary, I might can try "location" version 1 to integrate.
I will include build.gradle commits for now.
=> Issue 290 : Add example of showing current location

lib/src/map/flutter_map_state.dart
I spent a little while in the debugger trying to figure out why a plugin wasn't working.
The answer: I didn't include it in the options. Hopefully this will help. Optionally,
instead of returning null, this method could return some sort of null Widget, so that
a plugin issue doesn't cause the map to fail to render.
=> Adding an explanation when a plugin has not been activated

lib/src/layer/tile_provider/mbtiles_image_provider.dart
Added a third parameter to the MBTileImage to distinguish two different MBTileImages with the same coordinates.
Fixes #545
=> Fix Bug 545 stacked MBTileImageProvider

lib/src/layer/tile_layer.dart, lib/src/layer/tile_provider/tile_provider.dart
Hello, I made some changes to support simulating retina mode (_note: If geoserver supports retina `@2` tiles then it it advised to use them instead of simulating_).
It won't detect if device supports retina because I don't want force user to use `Material app` because of `MediaQuery.of(context)`.
However it is documented how to use it:
```
/// If `true`, it will request four tiles of half the specified size and a
/// bigger zoom level in place of one to utilize the high resolution.
///
/// If `true` then MapOptions's `maxZoom` should be `maxZoom - 1` since retinaMode
/// just simulates retina display by playing with `zoomOffset`.
/// If geoserver supports retina `@2` tiles then it it advised to use them
/// instead of simulating it (use {r} in the [urlTemplate])
///
/// It is advised to …
```
=> Support retina mode

lib/src/layer/tile_layer.dart
Hello, this PR adds support for detecting URL changes / tileSize changes / updateInterval changes and reloads Tiles if necessary.
closes #583
=> Observe TileLayerOptions changes

lib/src/layer/tile_layer.dart
Hi, this PR resolves #578 `Flicker on double click zoom` issue which was introduced by #572.
Flicker gif:
Patch gif:
=> fix Flickering bug - on double click / MapController move

lib/src/layer/group_layer.dart
The rebuild group stream created in `flutter_map_state.dart` isn't being consumed in the group layer, in my case causing polygons and markers to be shown where they aren't because those layers aren't being rebuilt.
The stream passed down to the layers inside the group layer are only the `option.rebuild` stream of each specific layer, and those streams are only populated when the dev is instantiating the `LayerOption` for that layer. I added a stream builder to rebuild all the layers inside the group layer, and left the current way the other layers are being handled, case the dev wants to rebuild a specific layer with that layers `option.rebuild` field.
=> fix/group-layer-rebuid: consuming rebuild stream in group layer

README.md, lib/flutter_map.dart, lib/src/layer/tile_layer.dart, lib/src/map/map.dart
I had the need to init a map widget by providing bounds to to constructor. 
The way it works is you just provide bounds and boundsOptions instead of the center. If no bounds are provided, the library will work as in the past by using the center. This change is backwards compatible.
This problem was discussed in https://github.com/johnpryan/flutter_map/issues/255
=> Initialize map widgets with bounds or center

README.md
I noticed there are a lot of requests for how to add popups and having tried the suggested approaches myself I found there were some drawbacks including:
* The popup disappears once the marker disappears even though the popup is big enough to still be visible.
* The popup is not tappable.
* A fixed size was required for the popup.
* It was not easy to choose how it is positioned.
So I wrote my own code to handle this which I've since moved to a plugin:
https://github.com/rorystephenson/flutter_map_marker_popup
=> Add flutter_map_marker_popup to plugins in README.md

example/lib/main.dart, example/lib/pages/tile_loading_error_handle.dart, example/lib/widgets/drawer.dart, lib/src/layer/tile_layer.dart
Hi **flutter_map** team!
Here is desigion for issue #593 
- add errorTileCallback for handling errors while no tiles
- example how to use errorTileCallback
Main goal to catch this exception, is to notify user about internet connection lost.
=> Handle exception on move without internet connection

pubspec.yaml
This fixes the warning:
```
[deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
binding.getFlutterEngine().getDartExecutor(), "plugins.flutter.io/path_provider");
```
=> Fix deprecation

.gitignore, CHANGELOG.md, lib/src/layer/tile_layer.dart
Correctly dispose TileLayer and Tiles in the order required by the TickerProviderStateMixin. The AnimationController in the tiles was not being disposed at all. After this change `_pruneTiles` sometimes gets called after the widget is already disposed - added a mounted check to prevent this.
=> Fix #595 TileLayer not getting disposed correctly

README.md, example/android/gradle.properties, example/lib/main.dart, example/lib/pages/widgets.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/layer/circle_layer.dart, lib/src/layer/group_layer.dart, lib/src/layer/marker_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart, lib/src/map/map_state_widget.dart, pubspec.yaml
@johnpryan 
> I rewrite all my last PR 
> Compatible with plugins and can combine last way to use layers (with LayerOptions).
---
🎸 **No breaking changes**
---
🤖 _What's inside?_
- Adding `MapState.of(context)` to get the current MapState
- Adding `forceRebuild` method on MapState for rebuild all map
- Can use simple widget with FlutterMap now with the new property `children`
- Fix initState/dispose lifecyle -> called after TileLayer code
📜 _More explanation_
__What the sort in stack with children and layers?__
`children` property is before `layers` property in stack of Widget.
__I want create a simple plugin, how?__
Use simple Flutter Widget, example `Text("I'm a simple plugin now")`
__I want create a plugin who can access to mapState, how?__
Create a Flutter Widget with …
=> feat(*): widget layers

lib/src/layer/tile_layer.dart
Hello, this PR make sure the `loadTileImage`'s listeners runs after the `tile` is in `_tiles` map .
```dart
/// Adds a listener callback that is called whenever a new concrete [ImageInfo]
/// object is available or an error is reported. If a concrete image is
/// already available, or if an error has been already reported, this object
/// will notify the listener synchronously.
///
/// If the [ImageStreamCompleter] completes multiple images over its lifetime,
/// this listener's [ImageStreamListener.onImage] will fire multiple times.
///
/// {@macro flutter.painting.imageStream.addListener}
void addListener(ImageStreamListener listener) {
```
> If a concrete image is already available, or if an error has been already reported, this object will notify the listener synchronously.
Since this …
=> Fix gray tiles when tile image is already avaible

example/lib/pages/plugin_api.dart, example/lib/pages/scale_layer_plugin_option.dart, example/lib/pages/zoombuttons_plugin_option.dart, lib/src/layer/circle_layer.dart, lib/src/layer/group_layer.dart, lib/src/layer/layer.dart, lib/src/layer/marker_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer.dart, lib/src/map/flutter_map_state.dart
This PR adds some key management feature for this project.
_Basicly keys preserve state when widgets move around in the widget tree._
There was two problems:
1. If I have forexample 3 `TileLayer layers` (`I.`, `II.`, `III.`) and if I swap `II.` and `III. widget layers` then `new II. layer` will have the `old II. layer's state` and `new III. layer` will have the `old III. layer's state` => so the loaded `_tiles` which are stored in state will have a hard time because it will show old tiles and panning will load new ones. If no keys provided then #584 PR will think url has been changed so the wrong `_tiles` will we reloaded, however this can avoided by using keys. This may happen forinstance if you want swap two wms layers.
2. In `flutter_map_state.dart` the `layerStack` may move around in …
=> Key management

example/android/app/src/main/AndroidManifest.xml
I wanted to 'feel' the performance of the flutter_map on android, by release building the example. 
Then I discovered no maps were loaded due to the release app not having INTERNET permission. I added the permission in the AndroidManifest.xml of the release configuration.
Br
Carl.
=> On Android: map loading in release build works now.

example/lib/pages/animated_map_controller.dart, example/lib/pages/home.dart, example/lib/pages/live_location.dart, example/lib/pages/map_controller.dart, example/lib/pages/marker_anchor.dart, example/lib/pages/on_tap.dart, example/pubspec.yaml
Tested with:
```
flutter build web
flutter build apk
```
This addresses the concerns raised in https://github.com/fleaflet/flutter_map/issues/774
=> Fixup build errors for the web example

lib/src/layer/tile_layer.dart
The option `overrideTilesWhenUrlChanges` currently only works if the URL
template changes but not if the options change.
For example:
```dart
TileLayerOptions(
urlTemplate: 'https://api.mapbox.com/styles/v1/mapbox/{id}/tiles/{z}/{x}/{y}',
additionalOptions: <String, String>{
'id': mapboxStyle,
},
```
If the value of `id` (here the Mapbox layer style, e.g. streets, satellite, etc.)
changes the option `overrideTilesWhenUrlChanges` should override the tiles as well.
=> Fix #629 | Reload map if options changed for overrideTilesWhenUrlChanges

lib/src/map/map.dart
If size has never been computed before `move()` is called on a `MapController` instance, there is a crash:
```
E/flutter (20522): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method &#039;/&#039; was called on null.
E/flutter (20522): Receiver: null
E/flutter (20522): Tried calling: /(2.0)
E/flutter (20522): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (20522): #1      MapState.getPixelBounds (package:flutter_map/src/map/map.dart:464:25)
package:flutter_map/…/map/map.dart:464
E/flutter (16529): #2      MapState.move
package:flutter_map/…/map/map.dart:307
E/flutter (16529): #3      MapControllerImpl.move
package:flutter_map/…/map/map.dart:41
E/flutter (16529): #4      MapAltState.initState.<anonymous closure>
``` …
=> Prevent crash when move() is called before FlutterMap has been built

README.md
Added recommended caching implementations for developers to use in readme (since flutter_map does not natively provide caching to reduce dependency requirements and since caching is such a use-case specific thing); **however** caching can be easily implemented with flutter_map using any Flutter ImageProvider that caches. This gives the app developer more control and reduces flutter_map maintainer load. Adding this to the readme will also lower the amount of Issues and PRs that add caching in many different ways when it should be handled by the developer.
Issues that this should close:
Fixes #832
Fixes #649
Fixes #576 (This issue will not be relevant to this repo and might still exist depending on ImageProvider)
Fixes #752 
Fixes #748 (Issue will not be relevant to this repo and still …
=> Add Caching Implementations to README

README.md
I wrote a plugin for user location last year. I think that it is simpler to use because it does not depend on other layer (No MapController or empty MarkerLayer are needed). The only things to do is adding the LocationMarkerLayer.
Example: 
```
Widget build(BuildContext context) {
return FlutterMap(
children: [
TileLayerWidget(
options: TileLayerOptions(
urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
subdomains: ['a', 'b', 'c'],
),
),
LocationMarkerLayerWidget(), // <-- add layer widget here
],
);
}
```
May I add this plugin into the readme? Thanks you
=> Add flutter_map_location_marker plugin to the plugin list

lib/src/layer/tile_layer.dart
The fix will iterate through the current tiles and check if any of them are outside the minZoom and maxZoom-values of the new BaseMap-layer. If so, it will stop flutter_map from trying to replace old tiles with the corresponding tiles from the new BaseMap.
=> Fix for Zoom-value outside min/maxZoom when changing BaseMap

lib/flutter_map.dart
Added two missing `@deprecated` flags to the `MapOptions` constructor (debug and interactive props) to warn the developers in their source code about the deprecation.
=> Add deprecated flags to constructor parameters

README.md
Hello,
Thanks for the great project! I have built this floating marker titles library for flutter, and flutter_map's code helped me a lot with that.
I'm hoping to give back by bringing value to your library by adding this feature, and I thought the best way to introduce this was with this PR, please let me know if there is a better way.
I hope this helps :-)
=> Listing flutter_map_floating_marker_titles under Plugins

lib/src/geo/latlng_bounds.dart
This PR is to add a pad function to the LatLngBounds class. The logic is based on Leaflet's pad function. This is useful when showing markers on the map with a bit of padding around the edges. Below are Leaflet's comments on the function.
// Returns bounds created by extending or retracting the current bounds by a given ratio in each direction.
// For example, a ratio of 0.5 extends the bounds by 50% in each direction.
// Negative values will retract the bounds.
=> Add pad function to LatLngBounds

lib/src/layer/polyline_layer.dart
Fix for Issue #856 
This fix Polyline border drawing bug introduced in version 0.11.0 PR #766 .
Causing the bug was that `borderPaint.style = PaintingStyle.stroke` was set after the drawing line `_paintLine(...,borderPaint)`, which made the drawing use the default `PaintingStyle.fill` causing the border to create a filled shape.
https://github.com/fleaflet/flutter_map/blob/e8389e13083839a9f854bba2239d91f475940eaa/lib/src/layer/polyline_layer.dart#L188-L195
Reordering the style set statement before the `_paintLine(...)` statement fixed the bug.
=> Fix #856: Polyline border drawing

lib/src/gestures/gestures.dart
This change fixes the fling acceleration issue reported in #271.
The initial rapid acceleration appears to be due to the spring physics being critically dampened. I changed the default to be over damped and tweaked it by manually comparing it to google and apple maps and now it's smoother.
Reference: [SpringDescription.withDampingRatio constructor
](https://api.flutter.dev/flutter/physics/SpringDescription/SpringDescription.withDampingRatio.html)
=> Update map fling spring physics parameters to reduce initial acceleration

README.md
Changed the following things in the README.md file:
- Added new plugin (flutter_map_tile_caching) to the plugins list.
- Removed obsolete tile caching guide.
- Clarified difference between new plugin and preconfigured offline maps.
=> Added new plugin to README

lib/src/layer/tile_layer.dart
Based on [this comment](https://github.com/fleaflet/flutter_map/pull/572#issuecomment-610269536), this PR adds a `fastReplace` option to `TileLayerOptions`.
The purpose of this option is to force tiles to be removed as soon as their replacement tile is ready, skipping `tileFadeIn*` options, as well as the hardcoded delay in `_tileReady()`.
These screenshots are based on [this config](https://github.com/pento/TidyWeather/blob/try/map-improvements/lib/cards/radar.dart#L71-L113): the top layer (the place names) uses transparent tiles.
Note how different zoom levels of the top layer are visible at the same time while zooming.
It no longer shows multiple zoom levels at the same time, though there is sometimes a small flicker where no tile is visible at all, even after the tiles have been …
=> Add a fastReplace option to TileLayerOptions.

example/lib/main.dart, example/lib/pages/stateful_markers.dart, example/lib/widgets/drawer.dart, lib/src/layer/marker_layer.dart
Fix issue https://github.com/fleaflet/flutter_map/issues/885 which prevent from preserving markers state.
A key was added to the `Marker` and used for the top level widget in the markers layer (the `Positioned`). This ensure that even if some markers are added / removed from the map, the `Stack` element is able to find the corresponding widget and then preserve its state instead of recreating a new one.
=> Add a key for markers to preserve state

CHANGELOG.md, README.md, analysis_options.yaml, example/pubspec.yaml, lib/src/core/bounds.dart, lib/src/gestures/gestures.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer.dart, pubspec.yaml
This PR fixes some typos in documentation, adds a Changelog and improves the pub/pana score by properly updating/editing the pubspec.yaml.
=> Random Fixes Everywhere

README.md
There are now 4 different ways of caching/downloading/preconfiguring offline mapping, so this PR aims to describe them all, and say which option is best for which use case.
I also fixed some capitalisation inconsistencies.
=> Clarification of all options available for offline mapping

lib/src/layer/group_layer.dart
All other `LayerOptions` constructor accept null key and null rebuild, `GroupLayerOptions` should also accept.
=> fix Group Layer Options constructor wrong nullability

example/lib/pages/animated_map_controller.dart, lib/flutter_map.dart, lib/src/map/map.dart
This PR adds a method to calculate the center of a given map bound.
Which is needed for animated camera transitions from one bound to the next.
This should help with #965
=> Added centerZoomFitBounds to MapController

example/lib/main.dart, example/lib/pages/map_inside_listview.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/map/flutter_map_state.dart
This is basically copy of https://github.com/fleaflet/flutter_map/pull/717 (since the PR creator does not seem intrested in implementing the commented option and PR is now stale). I saw that the PR is not  being merged because there is no option to developer if they want previous behavior. I have tried to add a bool in mapoptions to determine the type of behavior in the map.
Let me know if anything else is required. I want this feature to be implemented.
Thank You!
=> bugfix: Prevent parent ListView widgets from snatching scrolling gestures

README.md
I'd like to add vector_map_tiles to the readme so that it's more discoverable.
=> add vector_map_tiles plugin to readme

example/lib/main.dart, example/lib/pages/reset_tile_layer.dart, example/lib/widgets/drawer.dart, lib/src/layer/tile_layer.dart
This change supports the clearing of in memory tiles from the TileLayerState as described in  #666 
I created a separate Stream to manage reset events instead of using the LayerOptions rebuild stream as this is currently consumed by the onMove event subscriber and any changes to this may affect existing implementations using the rebuild. 
I have also added an example for resetting the a TileLayer
=> feat: support resetting TileLayer

example/lib/pages/scale_layer_plugin_option.dart, lib/src/geo/latlng_bounds.dart
A `LatLngBounds` object can now return its center midpoint.
Example usage:
```dart
var bounds = LatLngBounds.fromPoints([LatLng(1, 1), LatLng(0, -1)]);
print(bounds.center);
// LatLng(latitude:0.500076, longitude:-0.000076)
```
[The resource used for the maths](http://www.movable-type.co.uk/scripts/latlong.html)
=> feat(LatLngBounds): Center LatLng getter

example/lib/pages/custom_crs/custom_crs.dart, example/lib/pages/tap_to_add.dart, lib/flutter_map.dart, lib/src/gestures/gestures.dart
This PR added the Screens TapPosition to the onTap Callback. 
When using an interactive WFS Service that handles Click/Touch Inputs you need to pass the Screen Position to Pressed to the Service, not the LatLong point.
If you use a separate GestureDetector stacked on top of FlutterMap it interferes with its Gestures (like Pan oder Pinch). This PR exposes the TapPosition from FlutterMaps own GestureDetector.
Related to https://github.com/fleaflet/flutter_map/issues/706
=> Added TapPosition to TapCallback

CHANGELOG.md, pubspec.yaml, tool/history.sh
=> Prepared for release of 0.14.0

lib/src/map/map.dart
Proposed fix for issue mentioned in #1002
=> Remove inappropriate null-aware checking to moveAndRotate

example/lib/pages/zoombuttons_plugin_option.dart
In this example, when zooming in or out, the test against the int min and max zoom fails as the cast "as double" fails.
In addition the min and max tests are the wrong way round.
Finally, if the zoom hits a min or max, the min or max zoom isn't applied.
The fix includes changing the type of minZoom and maxZoom to double which does not effect other code that references it.
=> Fix examples ZoomButtonsPluginOption to check min and max properly

lib/src/layer/tile_layer.dart
Small but nasty type-problem, that won't let apply generic ==-overrides when extended.
https://api.flutter.dev/flutter/dart-core/Object/operator_equals.html
=> Corrected equals type for Coords

lib/src/gestures/gestures.dart, lib/src/map/flutter_map_state.dart
This fixes https://github.com/fleaflet/flutter_map/issues/946
Fling and double tap animations are already cancelled in multiple scenarios (like panning the map). This PR also cancels the animations whenever the `MapController` moves the camera. This is done to prevent interferences with animated camera moves.
=> Cancel animations on map controller move events

example/lib/pages/polyline.dart, lib/src/layer/polyline_layer.dart
=> #1119: fix LateInitializationError with polylineCulling

lib/src/layer/tile_layer.dart
Handle WMS server that only accepts boolean values as uppercase strings.
=> Encode boolean values as uppercase string in WMS request.

lib/src/gestures/gestures.dart
old behaviour on pinchzoom was to zoom in regarding the map center. now it zooms in regarding the center of the pinch gesture like in google maps for example. I didn't add an option to change between the two as i cant imagine anyone would want to zoom into the center of the map when using pinchzoom.
=> Pinchzoom regarding gesture center

lib/src/layer/marker_layer.dart
Don't merge this without testing/checking. I'd like some thoughts first on whether we want an option to turn caching off, and if using map.var rather than widget.map.var is preferred or not. 
There's recently been a crash on MarkerLayer where the pxCache and the Markers didn't match up, after adding a marker after a tap.
This is a suggestion that looks to prevent the crash from happening, making sure we update if the lengths mismatch. Also added the option to turn off pxCaching as it "could" get out of date I think. Default is on.
There may be a better solution.
=> Added option to use pxCache and also length check on Markers to avoid crash

lib/src/gestures/gestures.dart, lib/src/gestures/map_events.dart, lib/src/map/map.dart
This PR adds a `MapEventScrollWheelZoom` event that is fired when a scroll wheel occurs. Currently no event is triggered on scroll wheel (and zoom change)
=> trigger event on scroll wheel

lib/src/gestures/gestures.dart
This modifies the behaviour of scroll wheel zooming so that it mimics other map packages (such as Google Maps) by pinning the center of scaling under the mouse pointer. This works regardless of the rotation of the map.
=> Center scroll wheel zoom on mouse pointer

example/lib/main.dart, example/lib/pages/max_bounds.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/map/map.dart
This introduces a maxBounds parameter (I believe leaflet.js uses this param, so tried to be consistent with naming). This will take a LatLng Bounds object, and try to make sure that the map display area isn't outside the bounds.
It will try and "adjust" to the nearest edge point, rather than just failing, to allow smoother dragging if it would otherwise be too small.
Use LatLngBounds(LatLng(-90, -180.0), LatLng(90.0, 180.0)) if wanting to contain the full map, and have no gray borders, otherwise a smaller area to contain.
=> Fix gray borders

example/android/app/build.gradle, example/android/app/src/main/AndroidManifest.xml, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
Built the example app just now, and had to update some numbers. This pull request makes it compilable without errors or warnings.
=> Update example data

lib/src/layer/tile_layer.dart
This is a possible workaround for the flicker and hairline issues https://github.com/fleaflet/flutter_map/issues/1126 & https://github.com/fleaflet/flutter_map/issues/1156
It removes the Opacity widget (I'm not sure this is going to get fixed easily by Flutter, so think we will have to create our own), and introduces the opacity to the RawImage instead.
This feels possibly logical, however, I'm not confident on the Animated Tile stuff, so this may not be exactly the same.... I assume the opacity at this position is for fading in new tilesets/zooms ? If anyone knows this part of the code, it would be useful to give some thoughts, as I'm a little unsure how to test it properly.
It would also be useful for those with the initial problems to see if it helps.
Rotation needs to be disabled for …
=> possible fix for opacity widget causing hairlines and possible flicker

README.md
Added link to <https://fleaflet-docs.netlify.app>, and link to #992 to leave feedback.
Made Discord link more prominent, along with beta documentation section.
No other changes.
=> Added beta documentation link to README

lib/src/layer/polyline_layer.dart
Solve #1217 
- Added saveLayers parameter to PolylineLayerOptions & PolylinePainter to enable or disable calls to canvas.saveLayer & canvas.restore (by default at `false` as advised in [ibrierley's comment](https://github.com/fleaflet/flutter_map/issues/1217#issuecomment-1101791862))
- Replaced calls to path.lineTo by path.addPolygon in PolylinePainter._paintLine (recommended here: https://github.com/fleaflet/flutter_map/issues/1165#issuecomment-1055342364)
=> refacto: added saveLayers parameter

lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
Fix for problem where bounds sometimes breaks on an initial layoutBuilder that doesn't have a valid constraints size, and causes fixBounds to break. (sorry created a branch here, but didn't mean to!)
=> Fix initial fit bounds

lib/src/layer/label.dart, lib/src/layer/polygon_layer.dart
Someone did a PR with centered labels but didn't finish it.
I did a few tweaks to use it in my project but I think it would be a good addition to the package
=> Creating centered label for polygons

lib/src/layer/label.dart, lib/src/layer/polygon_layer.dart, pubspec.yaml
Saw [this PR](https://github.com/fleaflet/flutter_map/pull/1220) about centered labels for polygons today.
I think it can be useful to add an option to place the label using [Dart polylabel](https://github.com/beroso/dart_polylabel). It works well on both convex and concave polygons.
Example:
| Centroid (current approach)  | Polylabel |
| ------------- | ------------- |
| <img width="234" alt="Screen Shot 2022-05-05 at 17 44 31" src="https://user-images.githubusercontent.com/7874200/167022894-1133b581-fc94-4de7-83d4-0fe45b9ef71a.png"> | <img width="224" alt="Screen Shot 2022-05-05 at 17 44 07" src="https://user-images.githubusercontent.com/7874200/167022958-ecc1703a-af4d-4de8-a2d1-b0711e305d0e.png"> |
=> Add polygon label placement options

example/lib/pages/tile_loading_error_handle.dart, lib/src/map/map.dart
As outlined in #1231, and discussed in Discord on 2022-05-11, certain zoom changes do not cause a move event to be emitted. This appears to be a bug, as probably everything changing the bounds should cause such an event. I am using flutter_map together with the flutter_map_marker_cluster plugin which e.g. zooms in if you tap on a cluster and thus changes the bounds, and I need to be able to react to that.
Therefore, I propose the following change to MapState._handleMoveEmit():
If source is custom, and targetZoom or targetCenter are different than before, a move event is emitted.
Thank you for your time and for flutter_map in general 😃
=> [BUG] Emit move event even when source is custom #1231

pubspec.yaml
I've notice that there are a couple of dependencies that aren't really being used.
=> Remove unused dependencies

analysis_options.yaml, lib/flutter_map.dart, lib/src/core/bounds.dart, lib/src/core/util.dart, lib/src/geo/crs/crs.dart, lib/src/geo/latlng_bounds.dart, lib/src/gestures/gestures.dart, lib/src/layer/circle_layer.dart, lib/src/layer/group_layer.dart, lib/src/layer/marker_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_builder/tile_builder.dart, lib/src/layer/tile_layer.dart, lib/src/layer/tile_provider/file_tile_provider_io.dart, lib/src/layer/tile_provider/file_tile_provider_web.dart, lib/src/layer/tile_provider/network_image_with_retry.dart, lib/src/layer/tile_provider/tile_provider.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart, lib/src/map/map_state_widget.dart, test/flutter_map_test.dart, test/helpers/core.dart
Mostly trivial code changes made by running `dart fix --apply`
The new most important rules enabled are:
- `prefer_final_locals`: https://dart-lang.github.io/linter/lints/prefer_final_locals.html
- `prefer_final_in_for_each`: https://dart-lang.github.io/linter/lints/prefer_final_in_for_each.html
- `avoid_dynamic_calls`: https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html
All three rules take advantage of relatively recent improvements in the Dart SDK and thus "modernize" the codebase (eg. getting rid of all those `var`), they can potentially have a positive impact on performance as described in the reference links while also ensuring correctness long term.
I've also re-enabled `library_private_types_in_public_api` that is present in `flutter_lints` and was overridden …
=> Enable stricter linter rules.

example/lib/main.dart, example/lib/pages/point_to_latlng.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/map/map.dart
I wanted to get LatLng of a given point on screen, but couldn't find an easy way to. 
So I've implemented a `MapController.pointToLatLng()` inspired by @maRci002's [answer](https://github.com/fleaflet/flutter_map/issues/607#issuecomment-628208311).
Ref #496, ref #607, ref #981, ref #1010
=> Added MapController.pointToLatLng() to get LatLng of given screen point

example/lib/pages/epsg4326_crs.dart
Redoing PR for none https link in example page after Git issue, causing errors when using Flutter web. Mobile is fine normally, this only affects browser.
=> Fix for example with web failing for non-https link 

lib/src/map/map.dart
There's an odd exception that gets created, when we use fitBounds and padding. Sometimes flutter_map can't get a "size" (widget size) immediately, and a padding is used. This causes flutter_map to have a zero size, and subtract a padding, leading to a negative size within getBoundsZoom() in map.dart.
I.e ```var size = this.size - padding;```
As it ends up with a negative size variable, it then hits the line  ```size = CustomPoint(math.max(0, size.x), math.max(0, size.y));``` which turns it into an Integer CustomPoint. However, project later needs a double. 
So we can either force it with setting math.max and use 0.0 instead of 0, or I guess we can add a .toDouble() on math.max(0, size.x).toDouble() if wanted to be more explicitly.
=> fix double/int exception

CHANGELOG.md, README.md, example/lib/pages/home.dart, lib/flutter_map.dart, lib/src/layer/attribution_layer.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_layer_options.dart, pubspec.yaml
Inline with #1040, this deprecates the old method of attribution via `attributionBuilder`, and replaces it with a new layer widget: `AttributionWidget`.
`AttributionWidget` is intended to be used inside `nonRotatedChildren`. Therefore, both the README, main example page, and in-code documentation reflect this. It now also aligns with the map as expected, unlike the old method.
Also provided is a quicker way to attribute by using `AttributionWidget.defaultWidget`, which automatically styles the widget similar to how it is seen elsewhere on the Internet. The example and README use this for demonstration.
Resolves #1040 by replacing #1012.
=> Changed Attribution Methods

lib/flutter_map.dart, lib/src/gestures/gestures.dart
The standard zoom speed using the mouse wheel does not fit all needs. It would be nice if it can be adjusted. This tiny code change allows to override the currently fixed value.
=> the zoom speed using the mouse wheel can be adjusted

lib/src/layer/marker_layer.dart
@ibrierley @JaffaKetchup please check and see if there is any hiding happening with your working projects.
Thank you very much for the discussion.
Fixes #918.
=> Proposed fix for unsymmetrical anchored markers disappearing

lib/src/layer/tile_layer/tile.dart
dispose the animation controller before creating a new one
=> dispose AnimationController

lib/flutter_map.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
There is a setter for a final error, which calls for an exception. And it came! 
Fixes #1288.
=> [v2.1.0] Fix `LateInitializationError` with `MapController`

.github/ISSUE_TEMPLATE/bug-report.yaml, CHANGELOG.md, lib/flutter_map.dart, lib/src/map/flutter_map_state.dart, pubspec.yaml
Designed to complement #1293. Added a `keepAlive` option (defaults to `false`) to `MapOptions`. Mixed in `AutomaticKeepAliveClientMixin` with `FlutterMapState`, and made necessary changes. Set `wantKeepAlive` getter to return the value of the `keepAlive` option.
Also contains the updates needed for v2.1.0 release. Waiting on all PRs marked with '[v2.1.0]' before merging this, as the CHANGELOG will need to be updated for each of them.
=> v2.1.0 Release & Keep Alive Functionality

CHANGELOG.md, lib/src/layer/tile_layer/tile_provider/network_no_retry_image_provider.dart, pubspec.yaml
_Replaces #1317 due to a Git messup_
This is essentially a blind fix, implementing https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code. Help with testing is appreciated, as I can't see what I'm fixing!
Also upgraded package version to v2.1.1.
=> Fixed Null-Safety Errors

.github/workflows/delete_old_runs.yml, .github/workflows/flutter.yml, .github/workflows/stale.yml, lib/src/layer/tile_layer/tile_provider/network_no_retry_image_provider.dart
#1318 appears not to have gotten all the possible bugs in the concerned line. This should get them all!
Also includes all changes from #1321.
=> Addition To #1318: Null-Safety Bug Fix

example/lib/pages/overlay_image.dart, lib/src/layer/overlay_image_layer.dart
Currently the OverlayImage layer only accepts a rectengular bounding box based on two corner points.
This doesn't allow rotating overlaid images like it is possible in other map frameworks.
[Mapbox for example](https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/) requires a latitude/longitude for each corner of the image.
For Leaflet the following plugin/layer exists which just requires 3 points to be defined (because it derives the 4th point itself): https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated
This PR is based on the beforehand mentioned `Leaflet.ImageOverlay.Rotated` layer and adds a third point to rotate/skew the image.
=> [v2.2.0] Add Rotation Capability To `OverlayImage`

example/lib/main.dart, example/lib/pages/latlng_to_screen_point.dart, example/lib/widgets/drawer.dart, lib/flutter_map.dart, lib/src/map/map.dart
Recreation of PR #1325 due to issues.
=> Added latLngToScreenPoint and refactored pointToLatLng

example/lib/pages/polygon.dart, lib/src/layer/label.dart, lib/src/layer/polygon_layer.dart
When set in the Polygon, rotation will keep the polygon labels facing the top of the display similar to rotation of a marker.  Rotation is about the center of the text.
=> Add polygon label rotate

example/lib/pages/scale_layer_plugin_option.dart, lib/src/geo/crs/crs.dart, lib/src/geo/latlng_bounds.dart, lib/src/layer/circle_layer.dart, lib/src/map/flutter_map_state.dart
- Fixes https://github.com/fleaflet/flutter_map/issues/1346
- `LatLngBounds.fromPoints` converted degrees to radians, then radians back to degrees... Also used num and nullables although we were only dealing with doubles.
- Removed some unnecessary casts coming from inferred types (where double can be inferred rather than num).
Not sure if we can guarantee that all `CustomPoint<num>` are in fact doubles, but left them for now since it would be a bigger change.
=> Reduce unnecessary casts, use convert when unsafe

example/lib/pages/epsg3413_crs.dart, example/pubspec.yaml, pubspec.yaml
Upgrades the project to the latest compatible dependencies.
Also adds `assets/` path prefix to a broken `Image.asset()` in the EPSG:3413 example.
Tested on all examples, seems to work except for https://github.com/fleaflet/flutter_map/issues/1360.
=> Upgrade dependencies, fix EPSG:3413 example

lib/flutter_map.dart
I always wondered what the use of the `zoom` parameter of the `FitBoundsOptions` class was.
When working on #1367 I finally had the chance to look into it. As it turns out this parameter is never used nor is it documented.
Since this is a somewhat breaking change I made a separate PR.
=> Deprecate obsolete fit parameter

lib/src/map/flutter_map_state.dart
Possible fix for the recent ```bounds``` issue. Needs proper testing before merging as I'm not quite familiar with bounds and recent changes. 
What this does is remove the fitBounds in the build method (I'm not sure this is needed there at all, as long as its run once?), and move it just to the initState (but it looks like it needs to run in the WidgetsBinding.instance.addPostFrameCallback for it to take effect...I'm not entirely sure if this is best or if its better before/after options.onMapReady?.call()).
Few thoughts...should ```bounds``` (I think we should think of it as initialFitBounds if my understanding of it is correct, and maybe rename one day) only run here...are there any other situations when we need to reset bounds ? Are there any possible race conditions where this is in …
=> Fix `bounds` Issue (for #1362)

lib/src/layer/polygon_layer.dart
Fix #1401 
The code is inspired by the way keys are managed for the `Marker` class.
=> Add key to polygon

lib/src/layer/circle_layer.dart, lib/src/layer/polyline_layer.dart, pubspec.yaml, test/flutter_map_controller_test.dart, test/flutter_map_test.dart, test/layer/circle_layer_test.dart, test/layer/marker_layer_test.dart, test/layer/polygon_layer_test.dart, test/layer/polyline_layer_test.dart, test/test_utils/mocks.dart, test/test_utils/test_app.dart
I've added a key property to `Polyline` and `CircleMarker` classes. Moreover I've written some basic tests and made reusable test utilities.
I've replaced the `dev_dependency` to `mockito` by `mocktail` as it's easier to use and doesn't rely on code generation which might be cumbersome when testing.
The API is almost the same and doesn't change the current usage in `MockHttpClientResponse`, `MockHttpHeaders`, etc.
=> Add key to Polyline, CircleMarker + Test utilities

lib/src/gestures/gestures.dart
Hello!
I found a bug while you trying to scale map with enabled scaffold drawer. If youll try to zoom a map when one of your finger stays on drawer gesture hook, ScaleUpdateDetails with come with ScaleUpdateDetails.scale = 0, and _getZoomForScale will return infinity zoom
You can try to make this moves on example app or just check the video
https://user-images.githubusercontent.com/13536462/196762179-8bf50e6e-9b11-4be1-8656-4483c300866c.mp4
=> Fix ignore details.scale = 0 to prevent Unsupported operation: Infinity or NaN toInt

lib/src/map/flutter_map_state.dart
fitbounds doesn't work on initial frame when its on a fast device as it tries to display before it can get a size of the device, due to the nature of a layout builder. This tries to rectify one of the checks to toggle when a size is available for bounds checking.
Please test this thoroughly on mobile and on web. Pay especial attention for first frame adjustment flicker that could be annoying, checking that bounds in MapOptions behaves correctly.
=> Fix bounds/fitBounds not working on first display.

lib/src/layer/polyline_layer.dart
Implementation: 
- useStrokeWidthInMeter boolean parameter. When that value is true the PolylinePainter use the map to get the stroke width in meters and render using that.
=> Polyline stroke width in meters

example/lib/pages/tile_builder_example.dart, lib/src/layer/tile_layer/tile_layer.dart
This is a possible example for https://github.com/fleaflet/flutter_map/issues/1337 (nice PR number btw :D) if I'm understanding it correct. (preloading can be slightly ambiguous).
Note, this extends the tilerange in each direction by an integer, and will affect performance, maybe good in one sense, for preloading for panning, but the extra tileloads will have some extra impact in terms of waiting for tile loads, decoding, potential costs etc. So this needs some extra thought and testing if it's really what we want.
If this is purely for panning only, it could be more efficient to only load tiles ahead of the direction that's being panned (lets say we pan +X,-Y we don't need to extend -X,+Y), but that would probably add some extra complexity.
Needs proper testing :).
=> Add panBuffer feature to include extended tilerange

CHANGELOG.md, pubspec.yaml
- Updated CHANGELOG
- Updated pubspec.yaml version
=> Prepare for v3.1.0 release

example/lib/pages/tile_builder_example.dart, lib/src/layer/tile_layer/tile.dart, lib/src/layer/tile_layer/tile_builder.dart
The commits are self-explanatory. These fixes ensure that the package scores 140/140 in pub.dev.
=> Fix deprecations and minor linter warnings

lib/src/geo/latlng_bounds.dart
The method fails to deal correctly with LatLng wrap arounds. A more correct version would probably look more like:
void pad(double bufferRatio) {
final heightBuffer = (_sw!.latitude - _ne!.latitude).abs() * bufferRatio;
final widthBuffer = (_sw!.longitude - _ne!.longitude).abs() * bufferRatio;
final point1 = LatLng((90 + _sw!.latitude - heightBuffer) % 180 - 90,
(180 + _sw!.longitude - widthBuffer) % 360 - 180);
final point2 = LatLng((90 + _ne!.latitude + heightBuffer) % 180 - 90,
(180 + _ne!.longitude + widthBuffer) % 360 - 180);
final newBounds = LatLngBounds(point1, point2);
_sw = newBounds.southWest;
_ne = newBounds.northEast;
}
On a tangent, it probably should be a factory rather than a mutable method and the `bufferRatio` parameter is hard to use correctly. For example, bufferRatio …
=> Delete unused and broken LatLngBounds.pad() method.

example/lib/widgets/drawer.dart
Tiny change to the drawer naming of `tap_to_add.dart` to match the file's App Bar. I believe this makes it easier to find the file within the example's `lib` directory after browsing through a built version of the Example.
=> renaming "add pins" in drawer to match file

CHANGELOG.md, example/lib/pages/polygon.dart, example/lib/pages/polyline.dart, lib/flutter_map.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer/tile_layer.dart, pubspec.yaml, test/layer/polygon_layer_test.dart, test/layer/polyline_layer_test.dart
The batching is based on @MooNag 's proposal.
Based on a makeshift benchmark and my phone, I'm seeing:
* On the raster thread:
* max: 2521ms => 8ms  (314x improvement)
* avg: 1219ms => 6ms  (202x improvement)
* On the UI thread:
* max: 49.6ms => 3.6ms (12.7x improvement)
* avg: 19.2ms => 2.0ms (8.6x improvement)
* Before: 
* After:
=> Batch canvas draw operations and minimize redraws on map pans for the polygon and polyline layers to significantly improve performance.

example/lib/pages/map_inside_listview.dart, lib/flutter_map.dart, lib/src/map/flutter_map_state.dart
The only reason to disable absorbing of pan events is because some plugins which use drag gestures rely on it. It turns out if those plugins detect vertical/horizontal drag instead of pan this flag is not necessary.
Note that affected plugins need to be updated and this should be released in a major version bump as it is a breaking change.
See #1454 discussion leading to this PR.
- When `absorbPanEventsOnScrollables` is true a horizontal & vertical drag gesture detector are added to FlutterMap and if they are triggered FlutterMap's scale gesture logic is triggered since the vertical/horizontal drag gesture and scale gesture are in the same `GestureArenaTeam` and the scale gesture is the captain of that team. Horizontal/vertical drag gestures are recognised faster than scale/pan gestures …
=> Remove absorbPanEventsOnScrollables option

example/lib/pages/scale_layer_plugin_option.dart, example/lib/pages/zoombuttons_plugin_option.dart, lib/src/layer/attribution_layer/rich.dart, lib/src/layer/circle_layer.dart, lib/src/layer/marker_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/map/flutter_map_state.dart
Refactored `FlutterMapState`'s `maybeOf` method into itself and `of` to meet good practise guidelines and avoid unnecessary nullable return types.
Also changed the error that `of` throws from `FlutterError` to `StateError`.
=> Refactored `FlutterMapState`'s `maybeOf` method

CHANGELOG.md, example/lib/pages/custom_crs/custom_crs.dart, example/lib/pages/epsg3413_crs.dart, example/lib/pages/latlng_to_screen_point.dart, example/lib/pages/scale_layer_plugin_option.dart, lib/flutter_map.dart, lib/src/core/point.dart, lib/src/geo/crs/crs.dart, lib/src/gestures/gestures.dart, lib/src/layer/tile_layer/tile_range.dart, lib/src/layer/tile_layer/tile_range_calculator.dart, lib/src/map/flutter_map_state.dart, lib/src/map/map.dart, test/core/bounds_test.dart, test/layer/tile_layer/tile_bounds/crs_fakes.dart, test/layer/tile_layer/tile_range_test.dart
1. `CustomPoint<int>` is not used in this plugin explicitly: change CustomPoint to always double to avoid potential error.
2. Some property are num and some are double, but seem having no good reason: change to double for consistency.
3. `mapState.nonrotatedSize` and `mapState.size` is always available after widget initlized: change its getter to non-nullable.
4. `CustomPoint.multiplyBy()` have same functionality as `operator *`: make as deprecated.
=> Normalize num type

lib/src/map/flutter_map_state.dart, lib/src/map/map.dart
FlutterMap4 changes project()'s return type from CustomPoint<num> to CustomPoint<double>, henceforth push the stricter typing further up the stack and do some opportunistic cleanups/fixes.
=> Apply stronger typing of FlutterMap4 more broadly and opportunistic cleanup/fix

lib/src/map/flutter_map_state.dart, test/flutter_map_test.dart
Previously, the broad dependency triggered rebuilds when the keyboard came up even when rendered in a Scaffold() with resizeToAvoidBottomInset set to false. This caused a lot of jank for me, i.e. triggering full-map-rebuilds at animation pace.
=> Fine-grained MediaQuery dependencies to rebuild only when needed

lib/src/layer/tile_layer/tile_provider/network_image_provider.dart
This MR should fix https://github.com/fleaflet/flutter_map/issues/1554.
Reason:
If no tile image exists, then retry only if a fallback url is defined. Otherwise rethrow the exception.
=> Change: rethrow exception if no fallback url is defined (FlutterMapNetworkImageProvider)

example/lib/pages/markers.dart, lib/src/layer/marker_layer.dart
This addresses #1552, it re-instates the precalculated Anchor on a Marker whilst leaving the argument as an anchorPos which makes it consistent with the MarkerLayer options.
=> Improve `Marker.anchor` performance

lib/src/map/camera/camera_fit.dart
The `centerZoomFitBounds` is a very powerful method and can be used for a lot of different use cases.
Sometimes one doesn't only want to limit the `maxZoom` but the `minZoom` level. For example to ensure, that we won't zoom out past a certain zoom level even if this means that the supplied bounds won't fit entirely within.
Clamping the zoom afterwards doesn't work, because the center calculation depends on it.
=> Add `minZoom` property to `FitBoundsOptions`

lib/src/layer/tile_layer/tile_layer.dart, lib/src/map/options.dart, lib/src/map/widget.dart
Resolves #1577. Moved `backgroundColor` property from `TileLayer` to `MapOptions` (with deprecations).
=> Simplify background colouring when specifying multiple TileLayers

lib/src/layer/attribution_layer/animation.dart
Fixes #1589.
Added `IgnorePointer` to `FadeRAWA.popupAnimationBuilder` to ignore gestures when closed. `ScaleRAWA` does not suffer from the same issue as the child becomes 0x0 px.
=> Ignore gestures on closed `RichAnimationWidget` when using `FadeRAWA`

example/lib/pages/polygon.dart, lib/src/layer/polygon_layer.dart
Fix some polygon edge cases, e.g. double drawing on labels or not correctly setting the border color.
I also feel that the code re-organization really helped the separation of concerns and made it much clearer what each part is doing. Specifically:
* Fill and border are clearly separated.
* The loop is only responsible for batching paths. The Paint is now handled once during drawing.
=> Fix some polygon edge cases, avoid unecessary work, and tidy up the code

example/lib/pages/polygon.dart, lib/src/layer/polygon_layer.dart, test/layer/polygon_layer_test.dart
This PR addresses a pre-existing condition and is independent from the cleanup. The cleanup is more a result of my debugging. The commits could be split.
=> Fix polygon draw batching

example/lib/pages/interactive_test_page.dart, lib/src/gestures/flutter_map_interactive_viewer.dart, lib/src/gestures/interactive_flag.dart, pubspec.yaml
Resolves #1445. 
Also improved the example app's Interactive Flags page with reduced maintenance cost and more suitable design.
NOTE: This does not ~resolve~ #1602.
=> Added `InteractiveFlag.doubleTapDragZoom`

lib/src/layer/label.dart, lib/src/layer/polygon_layer.dart
This change contains all previous micro-optimizations plus a larger optimization extending the scope and applicability of polygon draw batching.
Previously, we'd eagerly flush a batch whenever we'd encounter a polygon with a label. However, depending on the rendered polygon and label size, it would never be drawn. In this case we don't have to and should flush.
From a composition and visual point of view, this change is a noop.
=> Increase scope of polygon draw batching for polygons with labels.

lib/src/map/camera/camera.dart
This will ensure assertions like the one described in [this issue](https://github.com/fleaflet/flutter_map/issues/1613) work as intended.
=> Implement `MapCamera` equality & `hashCode`

example/lib/main.dart, example/lib/pages/cancellable_tile_provider/cancellable_tile_provider.dart, example/lib/pages/cancellable_tile_provider/ctp_impl.dart, example/lib/widgets/drawer.dart, example/pubspec.yaml, lib/src/layer/tile_layer/tile_error_evict_callback.dart, lib/src/layer/tile_layer/tile_image.dart, lib/src/layer/tile_layer/tile_image_manager.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_provider/base_tile_provider.dart, lib/src/layer/tile_layer/tile_provider/network_tile_provider.dart, lib/src/layer/tile_layer/wms_tile_layer_options.dart, test/layer/tile_layer/tile_image_view_test.dart
Closes #1430. Note that this doesn't provide an implementation of a `TileProvider` that actually cancels HTTP requests, as this is currently unavailable without Dio (see #1430's thread for more info). It just implements the infrastructure necessary to allow an implementation.
To test the cancellation support, install Dio, and try these code blocks on top of this branch. Then, run on the web, and open the browser's DevTools Network tab. Observe how some requests are marked as "(cancelled)". Note that this is more apparent with slower tile servers, so using the default OpenStreetMap tile server likely won't cause too many cancellations.
<details>
<summary>network_tile_provider.dart</summary>
```dart
import 'package:flutter/rendering.dart';
import …
```
=> Added cancellation support to `TileProvider` and surrounding mechanisms

lib/src/gestures/flutter_map_interactive_viewer.dart
Fixed #1465, and potentially other issues.
=> Set `hasGestures` `true` in `_onPointerSignal`'s `move` invocation

lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_provider/network_image_provider.dart
Fixes #1628.
Implemented a simple equality operator that just compares the URL. If a fallback URL is specified, caching is disabled to avoid potential issues.
There's no point comparing the HTTP `BaseClient`, because they are never equal unless they are identical, which they are not. Deeply comparing the `headers` map could be expensive, and usually headers don't change within the same session anyway.
=> Added memory caching support to `FlutterMapNetworkImageProvider`

example/lib/pages/polygon.dart, lib/src/layer/label.dart, lib/src/layer/polygon_layer.dart
Computing polylabel positions is insanely expensive eating up some 70% of my UI thread render times.
=> Compute label position in map/coordinate space rather than pixel space

lib/src/map/internal_controller.dart
Fixes #1563. However, this is a quick fix, and does not resolve the root of the problem. I'm not sure why `MapEventSource.mapController` acts differently to `MapEventSource.fitCamera`.
=> Changed `FlutterMapInternalController.fitCamera`'s `source` to `MapEventSource.mapController`

lib/src/layer/tile_layer/tile_layer.dart
Fixes #1625.
The issue was already apparently resolved in v6 'master', however, it did not appear that way due to a likely conflict between the default `maxZoom` and specified `maxNativeZoom`, where the `maxZoom`'s effect took priority.
Changes have been made to the defaults, as follows:
* `minZoom`: 0
* `maxZoom`: double.infinity
* `minNativeZoom`: 0 (non-nullable)
* `maxNativeZoom`: 19 (non-nullable)
Changes have also been made to the documentation to reflect more appropriate usage recommendations and remove/correct confusing information.
The internal `_clampToNativeZoom` implementation has also been massively simplified to use Dart's native `clamp` method.
=> Changed `TileLayer`'s default (native) zoom levels

example/lib/pages/markers.dart, lib/src/layer/marker_layer.dart
Fixes #1500. `Marker.rotateAlignment` is now automatically adjusted, where possible, to fix incorrect anchoring when `rotate` is `true`.
Also:
* Removed `AnchorAlign` (without deprecation), preferring `Alignment`
* Added new documentation
=> Fixed incorrect `Marker` anchoring when counter-rotating

lib/src/map/options.dart
Fixes #1646.
I noticed that internally `MapOptions` were only updated if they differed from the old ones. However, the `==` operator did not check for `backgroundColor`, and neither did `hashCode`.
=> Fixed `MapOptions.backgroundColor` failing to update

lib/src/layer/tile_layer/tile_provider/network_image_provider.dart
When running a custom tile server, in the case of a missing tile we can get back zero bytes. Resulting in the **decode** function failure in **_loadAsync** of FlutterMapNetworkImageProvider.
Looking at the **_loadAsync** implementation, the call to the **decode** function was left out of the try/catch block. Simply moving the **decode** function call inside the try block fixes the issue - the app no longer crashes on a missing tile.
=> Fixed crash on uncaught "Invalid image data" exception

lib/src/layer/attribution_layer/rich.dart
Previously the widget waited two frames to find the dimensions it was allowed, then set the minWidth to be the width it naturally wanted. I think this was to ensure the widget took the full width of the screen. It was simple to set a Container's width to infinity to achieve the same thing, with less complexity.
I may have misunderstood the purpose, but either way it seems I get the same behaviour when tested.
=> Simplified the building of `RichAttributionWidget`

lib/src/layer/tile_layer/tile_provider/network_image_provider.dart, pubspec.yaml, test/layer/tile_layer/tile_provider/network_image_provider_test.dart, test/test_utils/test_tile_image.dart
Testing it fails and fallback appropriately under different http responses.
Currently the last test, "test load with invalid response (with successful fallback)" fails. The primary URL returns 200 OK but HTML not a image. The fallback URL is never attempted. Per the discussion on discord this may be a bug, however, it looks to fix this you need to go higher up the stack (I suspect TileImage) because the image isn't actually processed until then.
=> Fixed bugs and added tests for `FlutterMapNetworkImageProvider`

example/lib/main.dart, example/lib/pages/many_circles.dart, example/lib/widgets/drawer.dart, lib/src/layer/circle_layer.dart, test/layer/circle_layer_test.dart
I'm working on a project that requires a map with a lot of elements, while maintaining optimum performance.
At the moment, we have one custom painter per circle, which leads to a huge drop in performance when there are thousands of circles, for example, whereas we could just as easily use a single painter.
=> `CircleMarker` Performance Optimizations

example/lib/pages/animated_map_controller.dart, example/lib/pages/home.dart, example/lib/pages/many_markers.dart, example/lib/pages/map_controller.dart, example/lib/pages/markers.dart, example/lib/pages/moving_markers.dart, example/lib/pages/overlay_image.dart, example/lib/pages/point_to_latlng.dart, example/lib/pages/reset_tile_layer.dart, example/lib/pages/stateful_markers.dart, example/lib/pages/tile_builder_example.dart, lib/src/layer/marker_layer.dart, lib/src/layer/tile_layer/tile_layer.dart, test/flutter_map_test.dart, test/layer/marker_layer_test.dart
@ignatz:
~None of the individual changes is very critical. I'm not sure they're worth the API-breaking change. Maybe simplification + increase consistency can justify it. I can be swayed either way. Let me know what you think.~
---
@JaffaKetchup:
- No more `builder`s: now we use `Marker.child` for extra efficiency
- `Marker`'s constructor is now `const`ant, along with `MarkerLayer`
- `rotateOrigin` and `rotateAlignment` have been removed, as not sure of their valid use-case
- `Anchor`, `AnchorPos`, and all anchor terminology have been removed, to simplify
- Only relative `Alignment`s now supported, but now also non pre-provided ones
- Resolved confusion around meaning of anchors/position/alignment/relativity
Quite the breaking change!
=> Reworked markers

lib/src/layer/tile_layer/tile_layer.dart
It's not necessarily safe to assume a URL template will be provided when WMS options are missing.
Some plugins, for example, (*cough *cough FMTC) use `TileLayer` to transport other useful information, but not the URL itself.
=> Fixed bug where `null` `urlTemplate` caused exception in `TileLayer` construction

example/lib/pages/circle.dart, lib/src/layer/circle_layer.dart
Fix https://github.com/fleaflet/flutter_map/issues/1688
- Radius instead of diameters
- Fixed circles with only borders/filled with a transparent color
=> Fixed `CircleMarker`'s incorrect appearance and size

lib/src/map/options/options.dart
Quick fix #1682
Quick fix #1699 (I'm assuming)
Needs a more permanent fix in future, as the zoom gesture handling code obviously doesn't work quite right. Zoom should never be 'trapped' (#1699), and it should handle rubbing against bounds.
=> fix: Revert "Adjusted default `MapOptions.cameraConstraint` to prevent out-of-bounds viewing"

lib/src/misc/bounds.dart
It may be somewhat worth it just because Bounds are instantiated many times per frame. I might have seen some performance uplift qualitatively playing around in profile mode, and maybe fewer GC pauses but see for yourself or whether we consider this within margin :shrug:
=> perf: micro-optimize `Bounds`

lib/src/map/widget.dart
… every time.
In my profiles this contributed sometimes several percent. The effect is probably also exacerbated by many layers. Subjectively this felt like a noticeable impact if I trust my noisy environment.
=> perf: avoid unnecessarily creating new list on every frame

lib/src/layer/tile_layer/tile_bounds/tile_bounds_at_zoom.dart, lib/src/layer/tile_layer/tile_coordinates.dart, lib/src/layer/tile_layer/tile_image.dart, lib/src/layer/tile_layer/tile_image_manager.dart, lib/src/layer/tile_layer/tile_image_view.dart, test/layer/tile_layer/tile_image_view_test.dart
Consumed some single digit percent frame time for me. Improved contributions: 
* Don't compute hash of hashes.
* Cheap custom hash.
* Avoid string interpolation.
Also as a drive-by get rid of the TileCoordinates extends Point + zoom coordinate in favor of more consistent composition.
=> perf: reduce tile management overhead

lib/src/layer/attribution_layer/rich/widget.dart
When `showFlutterMapAttribution` is false, there is still a text "Made with 'flutter_map' that is displayed. This PR removes it.
=> fix: remove flutter_map text attribution when `showFlutterMapAttribution` is `false`

lib/src/layer/tile_layer/tile_bounds/tile_bounds.dart, lib/src/layer/tile_layer/tile_bounds/tile_bounds_at_zoom.dart, lib/src/map/options/options.dart
This pull request fixes the TileLayer.tileBounds property (issue https://github.com/fleaflet/flutter_map/issues/1710).
It was such a small bug that I overlooked it multiple times. 🥲
Additionally it fixes a typo and removes a duplicate variable.
<details>
<summary>See a minimal example here</summary>
```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
void main() => runApp(const MyApp());
class MyApp extends StatelessWidget {
const MyApp({super.key});
@override
Widget build(BuildContext context) {
return const MaterialApp(
home: TileBoundsTest(),
);
}
}
class TileBoundsTest extends StatelessWidget {
const TileBoundsTest({Key? key}) : super(key: key);
@override
Widget build(BuildContext context) {
return …
```
=> fix: repair `TileLayer.tileBounds`

lib/src/layer/polygon_layer/label.dart, lib/src/layer/polygon_layer/polygon_layer.dart
For ease of reviewing, I pulled the "polygon label"-only changes out of https://github.com/fleaflet/flutter_map/pull/1714 AND add TextPainter caching (which is actually the biggest cost reduction)
I could also add the TextPainter caching to https://github.com/fleaflet/flutter_map/pull/1714 but maybe we don't make that one even more sprawling. I'd suggest to review this one first and then I'll update https://github.com/fleaflet/flutter_map/pull/1714 .
=> perf(polygons): cull labels separately, and cache `TextPainter`

lib/src/geo/crs.dart, lib/src/layer/marker_layer.dart, lib/src/layer/overlay_image_layer.dart, lib/src/layer/polygon_layer/label.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/wms_tile_layer_options.dart, lib/src/map/camera/camera.dart, lib/src/misc/point_extensions.dart
Sorry, this combines a bunch of things that could be pulled apart. This is the result of me going on a spree trying to speed up Polygons, which are still the slowest experience in my App.
In a nutshell:
1. Cleaned up some internals in CRS. Addressed a couple potential sources for exceptions why may have been the reason for the whole try/catch. Arguably the recovery in the catch doesn't make much sense.
2. Then I noticed that pixelOrigin is rounding, which is plain wrong because Flutter operates on virtual pixels which can be fractional. So this rounding can introduce visual artifacts at no benefits.
3. Then I noticed that there's an entire family of Point extensions just to cover up the erroneous rounding. So I removed those (mostly). Also `scaleBy` is not a vector scaling operation. I …
=> perf!: remove unnecessary rounding and surrounding features, and produce less garbage

lib/src/geo/crs.dart, lib/src/layer/tile_layer/tile_bounds/tile_bounds.dart, lib/src/layer/tile_layer/tile_coordinates.dart, lib/src/layer/tile_layer/tile_image.dart, lib/src/layer/tile_layer/tile_image_manager.dart, lib/src/layer/tile_layer/tile_image_view.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_range.dart, test/layer/tile_layer/tile_bounds/tile_bounds_at_zoom_test.dart, test/layer/tile_layer/tile_image_view_test.dart, test/layer/tile_layer/tile_range_test.dart
A couple of performance improvements:
* cheaper data structures
* cheaper construction of stale Tiles
* add missing early abort to _reainChildren
* fewer allocations
* and just do not render tiles that are off screen.
=> perf!: reduce work to build and fix bugs in `TileLayer`, and improve culling of off-screen tiles

lib/src/gestures/flutter_map_interactive_viewer.dart, lib/src/gestures/interactive_flag.dart
=> fix: add `doubleTapDragZoom` and `scrollWheelZoom` to `InteractiveFlag.all`

lib/src/layer/circle_layer.dart
Since version 6.0.1 the circle layer is not updated properly any more.
This was introduced as a side effect of: https://github.com/fleaflet/flutter_map/commit/117f2543dc89f0fc0901be536f73d379adeba592#diff-5d1e8506fe899e135910abbab2ef61ca6b4fde4e34f60b80b0fd85204ae485baL40-L47
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
[before.webm](https://github.com/fleaflet/flutter_map/assets/13716661/801e99c2-b7c2-4ae5-af2f-d2ba159ce8b3)
</td>
<td>
[after.webm](https://github.com/fleaflet/flutter_map/assets/13716661/7c46e81b-77e5-48ba-86e5-f05798dd1585)
</td>
</tr>
</table>
This can also be tested using the example app's circle layer page by adding an `AnimatedSwitcher` around the `CircleLayer`.
```dart
AnimatedSwitcher(
duration: Duration(milliseconds: 300),
child: …
```
=> fix: CircleLayer not updating on pan

benchmark/crs.dart, example/lib/pages/custom_crs/custom_crs.dart, example/lib/pages/epsg3413_crs.dart, lib/src/geo/crs.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polyline_layer.dart, lib/src/misc/bounds.dart, lib/src/misc/offsets.dart, test/layer/tile_layer/tile_bounds/crs_fakes.dart, test/layer/tile_layer/tile_bounds/tile_bounds_test.dart
Sorry to any reviewer, this change looks wilder than it is. It should no be braking unless you were depending on Transformation which I now  made internal (should allow us to freely change APIs in the future). At the end of the day, I spend a significant effort to reduce the `math.Point` constructions and most importantly reduce virtual function call overhead.
There are also some minor simplifications:
* I moved things that don't need to be virtual into the base class since we're sub-typing anyway
* I moved transformation out of `Crs` and up a level since it didn't seem to fit the Proj4Crs well.
I found testing on a device a bit limiting so I ended up adding some micro-benchmarks (we can also drop 'em, no strong feelings). I always like to say: don't trust micro-benchmarks but I also …
=> perf!: optimize CRS performance and add micro-benchmark of limited expressiveness

lib/src/misc/position.dart
This PR adds a better value distribution of for `MapPosition.hashCode`.
Adding the 3 hashCodes together has the effekt that relativly bigger values are more likely to happen. This increases the chance of hash code collision.
```dart
@override
int get hashCode => center.hashCode + bounds.hashCode + zoom.hashCode;
```
If we use `.hashCode` anyway let's do the following change:
```dart
@override
int get hashCode => Object.hash(center, bounds, zoom);
```
Can and should get cherry picked to `v6.1.0-rc`
=> fix: `MapPosition.hashCode` value distribution

CHANGELOG.md, CONTRIBUTING.md, example/android/app/build.gradle, example/pubspec.yaml, pubspec.yaml, windowsApplicationInstallerSetup.iss
- Updated CHANGELOG
- Updated self versions throughout
- Updated dependencies
- Updated contributing guidelines
=> chore: v6.1.0 release preparation

lib/src/geo/latlng_bounds.dart, lib/src/gestures/map_interactive_viewer.dart
This PR is a follow up to https://github.com/fleaflet/flutter_map/pull/1743.
It makes use of the `radians2Degrees` from the `vector_math` package.
=> perf: use `radians2Degrees` const from `vector_math`

codecov.yml
I first had this change in https://github.com/fleaflet/flutter_map/pull/1757 but it's really annoing to review https://github.com/fleaflet/flutter_map/pull/1728 with all those warnings.
width="50%" />
That's why I moved those changes over to a new PR.
The changes can be seen in effect in https://github.com/fleaflet/flutter_map/pull/1757.
Last codecov pull request.™
=> chore: disable CodeCov coverage warnings in PR diff

lib/src/gestures/map_interactive_viewer.dart
This change fixes a minor bug in the gesture system: when initiating a double-tap-drag-zoom gesture, a tap on the map would be registered through the `MapOptions.onTap` callback.
=> fix: prevent double-tap-drag zoom gesture emitting a tap event

lib/src/gestures/map_interactive_viewer.dart
Reverts fleaflet/flutter_map#1796
Refs: 51f0d60
=> revert: prevent double-tap-drag zoom gesture emitting a tap event

example/lib/main.dart, example/lib/pages/many_circles.dart, example/lib/pages/many_markers.dart, example/lib/pages/polygon.dart, example/lib/pages/polygon_perf_stress.dart, example/lib/pages/polyline.dart, example/lib/pages/polyline_perf_stress.dart, example/lib/widgets/drawer/menu_drawer.dart, example/lib/widgets/number_of_items_slider.dart, example/lib/widgets/simplification_tolerance_slider.dart, example/pubspec.yaml, lib/src/gestures/positioned_tap_detector_2.dart, lib/src/layer/polygon_layer/label.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/polyline_layer/polyline.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/map/widget.dart, test/full_coverage_test.dart, test/layer/polygon_layer_test.dart
Reflected the same changes made to `PolylineLayer`. Also includes some minor performance enhancements and consistency changes to both.
Updated example project and improved consistency and styling. Added `PerformanceOverlay` widget to performance stress testing pages.
Also includes some other minor performance improvements (eg. wrapped `RepaintBoundary` around widget tree), and deprecates `Polygon.isFilled`.
=> perf!: add simplification caching to `PolygonLayer` & other performance improvements

lib/flutter_map.dart, lib/src/geo/crs.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polygon_layer/projected_polygon.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/misc/offsets.dart, lib/src/misc/simplify.dart, test/layer/tile_layer/tile_bounds/crs_fakes.dart
=> perf!: cache projection of polygon points & CRS improvements

lib/src/map/widget.dart
This is a really tiny change but a huge quality of life change - at least for me. 😅
=> refactor: make `FlutterMap.options` an optional parameter

example/lib/pages/gestures_page.dart, lib/src/map/gestures/services/drag.dart, lib/src/map/options/interaction_options.dart, lib/src/map/options/map_gestures.dart
(5) ~~Can no longer fling if drag gesture is disabled. On master, enabling fling without drag would start a fling if the normal conditions were met, but wouldn't drag/move if not, and wouldn't move whilst normal dragging.~~ 
Turn the fling gesture into an option for the drag gesture.
=> feat(gestures): fling animation as drag gesture option

example/lib/pages/gestures_page.dart, lib/src/map/controller/map_controller_impl.dart, lib/src/map/gestures/services/double_tap.dart
PR           |  Master
:-------------------------:|:-------------------------:
!<img alt="pr" src="https://github.com/fleaflet/flutter_map/assets/58115698/2e6f4d64-6142-423c-9d2c-7a8ebbd150ee">  |  <img alt="master" src="https://github.com/fleaflet/flutter_map/assets/58115698/fe9c01d0-8835-45ed-8d22-a8472771eaec">
https://github.com/fleaflet/flutter_map/assets/58115698/da44775d-4854-4665-b0c0-c2129393b7ba
- Fixed the emitted map events for `doubleTapZoomIn` and the fling animation of the `drag` gesture.
- I added callbacks for when an animation has ended or has been cancelled. It turned out that they are not used but having some callbacks for both events could make sense for the future. @JaffaKetchup you can decide if we keep or remove them.
=> fix(gestures): double tap zoom events, fling events

.github/dependabot.yml, .github/workflows/branch.yml, .github/workflows/daily.yml, .github/workflows/master.yml
removes all these depcrecation warnings
=> chore: bump versions of workflow actions, add to dependabot

lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polyline_layer/painter.dart
Hi!
Just tested the master version, and I noticed that my polygons no longer moved with the map, so here's the little fix.
=> Fix: repaint polygons/polylines on changes.

example/lib/pages/markers.dart, example/lib/pages/polygon.dart, example/lib/pages/polyline.dart, lib/src/layer/general/hit_detection.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polygon_layer/projected_polygon.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/map/options/options.dart, lib/src/map/widget.dart, pubspec.yaml
Resolves #385. Requires #1800 to be merged first.
This uses a similar format as to `Polyline` interactivity.
---
Helps to fix #1740.
- Hit testing is now performed even if there is no attached `hitNotifier`
- Any attached notifier is now notified about a successful hit even if there were no `hitValue`s
- `hitTest` internal output no longer depends on state of `hitNotifier`, to improve definitity without below...
---
Fixes #1740.
- This option caused unexpected behaviour in some cases, especially as it was enabled by default
- #1740 was caused because disabling it did not unwrap children, it just used the `translucent` property
- `TranslucentPointer` itself has been retained as it is a useful resource to further customize hit testing behaviour, and `CircleLayer` and `OverlayImageLayer` …
=> feat!: add interactive `Polygon`s, rework `Polyline` `hitTest` result, and deprecate/disable auto application of `TransulcentPointer`

lib/src/layer/polygon_layer/painter.dart
This works in the polyline layer, but I missed out a line copy when carrying some changes over.
Thanks to @mohammedX6 for bringing this to my attention. Replaces #1826.
=> fix: prevent null exception when undefined/null `Polygon.hitValue`

lib/src/layer/attribution_layer/rich/source.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/misc/bounds.dart
See the commit history, each change has it's own commit.
=> refactor: add assertions, remove redundant constructor, unnecessary private field

lib/src/layer/polygon_layer/painter.dart
fix #1829 
Problem was that as zooming in, path was getting very long and many dots was calculated eventually getting into millions and crashing. This resolves it by drawing points only on visible segment. Directly painting circles rather them on path. Thought this might be better. Any suggestions for improvement are welcome.  Would appreciate some testing as I haven't done much.
=> fix: prevent crash when zooming far into `Polygon`s

example/lib/main.dart, example/lib/pages/debouncing_tile_update_transformer.dart, example/lib/widgets/drawer/menu_drawer.dart, example/lib/widgets/notice_banner.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_update_transformer.dart
After some internal consideration, we believe we may have been slightly rushed in merging #1840.  
As I hinted to in my review comment, the underlying infrastrucutre to perform this debouncing mechanism was already available, just little known, relatively undocumented, and not fully complete.
This mechanism is the `TileUpdateTransformer`, a relatively power-user feature that allows the normal stream of `TileUpdateEvent`s emitted one-to-one with `MapEvents` to be transformed into a new stream. A `debounce`ing transformer has been implemented, which has the same effect as #1840, but without the new infrastrucutre that requires maintainence in future.
The example application has also been updated with a new demo page to show this.
The in-code documentation around the transformers has been …
=> feat!: added `TileUpdateTransformers.debounce` & reverted #1840

CHANGELOG.md, example/android/app/build.gradle, example/pubspec.yaml, pubspec.yaml, windowsApplicationInstallerSetup.iss
Requires #1850.
I've decided to change the way we do CHANGELOGs. It previously took me an hour or more to rewrite the entire commit list as a more readable format, and organise it. Therefore, I'm now just referring to the auto-generated list, which is now more acceptable that we're using conventional commits.
=> chore: prepare v7.0.0-dev.1 release

lib/src/layer/misc/line_patterns/pixel_hiker.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polyline_layer/painter.dart
* Changed the way to display the solid style segments (polygon and polyline), in order to fix a display side-effect.
* Some performance test should be performed to see if we're not significantly impacted, as we added a pre-computation step with potentially many allocations.
* That fix works only for lines, not for areas.
* `polygon_layer/painter.dart`: now using the new `SolidPixelHiker` for solid style display
* `polyline_layer/painter.dart`: now using the new `SolidPixelHiker` for solid style display
* `pixel_hiker.dart`: new `SolidPixelHiker` class
Example on high zoom level: the `path`s are unstable beyond a certain threshold, and as a side effect some painting are corrupted (in that case, the border). 
| before | after |
| -- | -- |
| …
=> fix: correct display of `StrokePattern.solid` at high zoom levels

lib/src/layer/misc/line_patterns/pixel_hiker.dart
Fixed a side-effect crash for both final dot and final dash.
Still, the display may look funny on final dash mode with `PatternFit.extendFinalDash`, but that's probably how it's supposed to work (e.g. not well at the end in special cases).
=> fix: 1874 - fixed side-effect crash for final dot / final dash

example/lib/pages/debouncing_tile_update_transformer.dart, example/lib/pages/polygon_perf_stress.dart, example/lib/widgets/drawer/floating_menu_button.dart, example/lib/widgets/number_of_items_slider.dart, example/lib/widgets/simplification_tolerance_slider.dart, lib/src/layer/attribution_layer/rich/widget.dart, lib/src/layer/attribution_layer/simple.dart
> info: 'background' is deprecated and shouldn't be used. Use surface instead. This feature was deprecated after v3.18.0-0.1.pre. (deprecated_member_use at [flutter_map_example] lib\pages\polygon_perf_stress.dart:99)
=> fix: remove deprecated members (for Flutter 3.22)

lib/src/geo/latlng_bounds.dart, lib/src/layer/polyline_layer/polyline_layer.dart
Some linestrings caused the PolylineLayer to throw an assertion exception.
```console
Assertion failed: file:///Users/matthiaskoch/.pub-cache/git/flutter_map-930e8b60e125e630e3c85ab373c0ebb8e9b08d70/lib/src/geo/latlng_bounds.dart:82:16
east >= west
"The west longitude can't be smaller than the east longitude"
packages/flutter_map/src/geo/latlng_bounds.dart 82:28                             unsafe
packages/flutter_map/src/layer/polyline_layer/polyline_layer.dart 171:41          [_aggressivelyCullPolylines]
packages/flutter_map/src/layer/polyline_layer/polyline_layer.dart 138:11          build
```
This bug was reported by borg_1of3 on discord: https://discord.com/channels/951867686378409984/1235305884620689558/1235305884620689558
The bug sneaked into the code base in …
=> fix: `PolylineLayer` throws exception: "The west longitude can't be smaller than the east longitude"

.github/workflows/branch.yml, .github/workflows/master.yml
Using the cache speeds up CI workflows.
This PR introduces a cache to:
- flutter
- java (gradle)
=> chore: use workflow cache

.github/workflows/branch.yml, .github/workflows/master.yml
To speed up workflows for PRs even further, we can start all jobs simultaneously.
We can't do this for the master branch CI to ensure, delivered builds have succeeded testing.
Before: [6m 47s](https://github.com/fleaflet/flutter_map/actions/runs/9095809907/usage)
After: [5m 57s](https://github.com/fleaflet/flutter_map/actions/runs/9111371623/usage)
=> chore(meta): start all PR workflow jobs simultaneously, use java 21

lib/src/layer/misc/line_patterns/pixel_hiker.dart, lib/src/layer/misc/line_patterns/visible_segment.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polyline_layer/painter.dart
Optimized the algorithm for "solid" polygon/polyline display.
The trick is to use `addPolygon` instead of numerous `moveTo`/`lineTo`. It looked like removing redundant `moveTo`s was quite effective, too.
Following are some perf tests. We're getting closer to the old solid algorithm (that we had to dismiss because of bugs in 25+ zooms).
| x | old solid algo | new solid algo | current PR |
| -- | -- | -- | -- |
| Raster (ms) | 206.2 | 578.9 | 208.6 |
| UI (ms) | 42.1 | 53.2 | 49.6 |
* `polygon_layer/painter.dart`: minor refactoring
* `polyline_layer/painter.dart`: minor refactoring
* `pixel_hiker.dart`: optimized the "solid pixel hiker" relying on `addPolygon` instead of numerous `moveTo`/`lineTo`
=> feat: optimization of "solid" polygon/polyline display

CHANGELOG.md, example/pubspec.yaml, pubspec.yaml
v6.2.0 will be a cherry pick of 4f6b524791b851363355e8577fda8e92a80051ba, plus dependency upgrades and necessary pubspec version changes only - these will not be committed.
=> chore: prepare for v7 & v6.2.0 releases

pubspec.yaml
Slightly downgraded package dependencies so that it works in flutter 3.19.
=> fix: downgraded some dependencies to re-introduce compatbility with Flutter 3.19

benchmark/point_in_polygon.dart, lib/src/geo/crs.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/misc/offsets.dart, lib/src/misc/point_in_polygon.dart, test/misc/point_in_polygon_test.dart
I mostly looked at the function because I wanted to use it myself but it was private. So I thought, if I expose it then I could at least put a ribbon on it by adding a benchmark and make it go wroom.
Before:
(duration: 0:00:05.998949, name: In circle)
(duration: 0:00:06.866919, name: Not in circle)
After:
(duration: 0:00:03.649496, name: In circle)
(duration: 0:00:04.611599, name: Not in circle)
Note, I opportunistically touched crs to remove the dart:ui dependency. This way it can be compiled with dart (w/o flutter) rendering the instructions in the benchmark correct again. Unfortunately, pointInPolygon is not so fortunate and needs flutter due to the dependency on ui.Offset. That's why I could only run it with "flutter test" in JIT mode.
=> perf: expose `isPointInPolygon` and make 40% faster (at least in JIT mode)

example/lib/pages/polygon.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon.dart
Fixes #1898.
Note that these new measures to ensure correct functionality could negatively impact performance. This is properly documented.
=> fix: overlapping `Polygon` cutting & color/translucency mixing

lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon_layer.dart
Also added helpful debugging tool to show triangulation output.
Fixes #1899.
=> fix: correct `PolygonLayer.useAltRenderer` renderer when `Polygon`s have multiple holes

example/lib/pages/home.dart, example/lib/pages/polygon_perf_stress.dart, example/lib/pages/polyline_perf_stress.dart, lib/src/layer/circle_layer/circle_marker.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polygon_layer/projected_polygon.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/layer/polyline_layer/projected_polyline.dart, lib/src/layer/shared/layer_interactivity/internal_hit_detectable.dart, lib/src/layer/shared/layer_projection_simplification/state.dart, lib/src/layer/shared/layer_projection_simplification/widget.dart
The main aim of this change is to enable each element to update independently only when required.
The pre-projection and pre-simplification logic have been refactored into their own state which can be mixed in (and is to `PolylineLayer` and `PolygonLayer`).
Performance results:
- There is little overall change (perhaps +<1ms on UI/build)
- On the stress test, update times have not changed much, but may have increased a bit - as expected
- It is expected that in many cases, this will improve efficiency of updates, because only the elements that have updated will need to be re-projected and re-simplified
- TLDR; there should be some overall noticeable change, except for extremely large samples where all elements change at once, where the behaviour can be manually controlled instead (see …
=> feat: implement efficient(-ish) change detection for `PolygonLayer` & `PolylineLayer`

pubspec.yaml
Unless we have a strong need for a higher version of `logger`, we can lower the dependency to `^2.0.0`
* `2.0.0` having been released in July 2023
* `2.3.0` being the latest version (May 2024)
It's used only for debug or benchmarks.
=> chore: relax dependency on 'package:logger'

CHANGELOG.md, example/lib/pages/home.dart, example/lib/pages/polygon.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/layer/shared/layer_projection_simplification/state.dart, lib/src/layer/shared/layer_projection_simplification/widget.dart, pubspec.yaml
Fixes #1924 and fixes #1921.
Effectively reverts some broken commits.
Note that `useDynamicUpdate` has been deprecated, but its functionality has changed - it now has no purpose. However, this will not be a breaking change, as `useDynamicUpdate` was broken when initially introduced, so there should be no legitimate users.
=> fix: fixed multiple issues in `PolygonLayer` and `PolylineLayer`

CHANGELOG.md, example/lib/pages/map_controller.dart, lib/src/map/controller/map_controller_impl.dart
Allows the MapController to get assigned multiple times to a view (only one a every time).
Can't tell much about potential side effects. Did some quick tests and everything worked alright so far but additional testing would be good.
- https://github.com/fleaflet/flutter_map/issues/1892
=> feat: allow reassignment of `MapController` to `FlutterMap` multiple times

lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/tile_layer/tile_layer.dart
Fixes #1934.
Removed an optimization that prevented the hit test to work for polygons on rotated maps.
=> fix: polygon hit detection when map is rotated

lib/src/gestures/map_interactive_viewer.dart, lib/src/layer/tile_layer/tile.dart, lib/src/layer/tile_layer/tile_coordinates.dart, lib/src/layer/tile_layer/tile_image.dart, lib/src/layer/tile_layer/tile_image_manager.dart, lib/src/layer/tile_layer/tile_image_view.dart, lib/src/layer/tile_layer/tile_layer.dart, lib/src/layer/tile_layer/tile_range.dart, lib/src/layer/tile_layer/tile_renderer.dart, lib/src/map/camera/camera.dart, test/layer/tile_layer/tile_image_view_test.dart, test/layer/tile_layer/tile_range_test.dart
Fixes #1582 (potentially eligible for bounty).
In a first approach I reused part of @ReinisSprogis' code regarding the camera using a -180,180 longitude.
The flash effect was due to tiles being somehow recreated when considered as from one world or another. The recreation is quick, but causes the flash effect.
The solution is to consider tiles in a unique -180,180 world AND to maintain a list of tile positions at the same time.
For instance, scrolling from Europe to Alaska:
* Alaska is first considered as from the next world
* scrolling again, Alaska is considered as part of the current world, as the center of the map is now in America
* the flash fix is about reusing the same tile image for both positions (next world, current world)
I tested only in the Polygon example (that has no …
=> feat: unbounded horizontal scroll

lib/src/layer/polyline_layer/polyline.dart
Should result in a performance improvement when using interactive polylines.
=> fix: remove `hitValue` from `Polyline.renderHashCode`

lib/src/layer/overlay_image_layer/overlay_image.dart
This PR introduces a filterQuality parameter to the OverlayImage widget, allowing developers greater flexibility in choosing the desired rendering quality.
=> feat: add `filterQuality` parameter to `(Base)OverlayImage`

lib/src/layer/overlay_image_layer/overlay_image.dart, lib/src/layer/overlay_image_layer/overlay_image_layer.dart
* Switch to `abstract` instead of `sealed`
* Renamed `_render` to `layout` (added protected metadata)
* Removed non-virtual metadata from `build`
* Replaced `Image.color` & `.colorBlendMode` for `opacity` support with normal `.opacity` field using `AlwaysStoppedAnimation`
* Removed ambient `MapCamera` from `layout` arguments
I feel like we're overcomplicating things, and maybe doing too much for the user? It's much more flexible if we allow the user to pass their own `Image`, and not much more difficult if we allow them to do so. I'm not sure if it would work, but then wouldn't any widget work (like https://github.com/TimBaumgart/flutter_map_polywidget), not just images?
=> feat: expose `BaseOverlayImage` for external implementation

lib/src/layer/shared/layer_projection_simplification/state.dart
The caching of the simplification was not working correctly, and creating massive overheads.
Essentially, we were storing a lazily-generated `Iterable` in the simplification cache. This means that it was fully re-generated (re-simplified) on every cache retrieval: simplification had to run every frame. We now store a non-growable `List`.
Before:
After:
=> fix(perf): fixed massive performance issue in simplification steps for `Polyline/gonLayer`s

lib/src/layer/tile_layer/tile_builder.dart
Hi there!
I love the library, it's very good.
However, I felt like the default dark mode filter could be improved somewhat.
It just only inverted the colours, which made the sea orange and the trees purple.
So I've figured out a nicer-looking dark mode filter!
It inverts the colours first, but then hue-rotates by 180 degrees to make the colours look normal again!
You can see it in action here:
Light:
Old dark mode:
New dark mode:
This hard-coded matrix was generated by the following Dart code:
```dart
// Using the `ml_linalg` package for the Matrix maths
//  https://pub.dev/packages/ml_linalg
// Matrices from https://www.w3.org/TR/filter-effects-1/#feColorMatrixElement
Matrix mat1 = Matrix.fromList([
[0.213, 0.715, 0.072],
[0.213, 0.715, 0.072],
[0.213, 0.715, 0.072],
]);
Matrix mat2 = …
```
=> feat(example): improve appearance of dark mode filter

example/android/app/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/lib/main.dart, example/pubspec.yaml
- Upgraded Android example Gradle versions
- Migrated away from deprecated 'package:url_strategy' on web
Also confirmed we support 16KB page size for Android 15.
=> chore(example): updated Android build config & migrated Web URL strategy

lib/src/layer/tile_layer/tile_layer.dart
fixes #1837
there are still some instances I can get the tiles to not prune when zooming, but i am not sure the exact conditions. it might be related to multi-level zooms, or prune timers? though it seems like they all appropriately callback.
As part of this PR i also looked to add optimistic tile pruning of the parent when all 4 children are loaded, however quickly ran into state consistency issues. This is a simple quick fix to resolve most of the problem, but the tile layer really needs a rewrite as some of the state is held inside of a `Manager` which cannot call setState when making changes to the tiles, leading to visual bugs, like this one. I tried to add a setState callback, but ran into flutter issues (as it is generally bad practice) to do this.
So as a mostly-fix, I am adding a …
=> fix: resolve most tile pruning/state issues

lib/src/layer/tile_layer/tile_provider/network_image_provider.dart, lib/src/layer/tile_layer/tile_provider/network_tile_provider.dart
Fixes #2010
`NetworkTileProvider` and `MapNetworkImageProvider` cannot be used with implementations of the http `Client` library.
Switch out incorrect `BaseClient` usage with `Client`.
- https://pub.dev/documentation/http/latest/http/BaseClient-class.html
- https://pub.dev/documentation/http/latest/http/Client-class.html
This fix uses the interface class and not the mixin implementation class that is used at the moment.
This change is backwards compatible and will not affect current usage of these classes as BaseClient implements Client interface.
@JaffaKetchup I am working on a project that would need this change. I'd be most greatful if we can get this out in a release. Thanks!
=> fix: use `Client` instead of `BaseClient` in network tile/image provider

lib/src/layer/tile_layer/tile_provider/network_tile_provider.dart
=> fix: avoid closing externally created `http.Client` in `NetworkTileProvider`

example/lib/pages/circle.dart, example/lib/pages/multi_worlds.dart, lib/src/layer/circle_layer/painter.dart
Now `CircleMarker`s are replicated on all visible worlds.
That includes both display and hit detection.
Some refactoring involved.
Impacted files:
* `multi_worlds.dart`: added a couple of `CircleMarker`s
* `painter.dart`: added replication of circle display and hit detection on all visible worlds
=> feat: add multi-world support to `CircleMarker`s

example/lib/pages/multi_worlds.dart, lib/src/map/camera/camera.dart
- Tapping on the map will be redirected to the main world, instead of being truncated on a -180 or 180 longitude.
- Fixes #2008.
* `camera.dart`: now looking for the best world before unprojecting a pixel
* `multi_worlds.dart`: added an `onTap` event to create on the fly markers
=> fix: invoke map interaction callbacks with coordinates in primary world

lib/src/map/controller/map_controller_impl.dart
=> fix: ensure `MapController.rotateAroundPoint` does not move map when already rotated

lib/src/gestures/map_interactive_viewer.dart
=> fix: ensure movement gestures emit events when starting

CHANGELOG.md, example/pubspec.yaml, lib/src/layer/polygon_layer/label.dart, lib/src/layer/shared/feature_layer_utils.dart, pubspec.yaml, windowsApplicationInstallerSetup.iss
This #2052 fix is made of 2 separate parts.
One part is saying "No!" to forever loops: we assume that after trying to display on multiple worlds, if we keep trying it's because we'll never get an exit permit. And in that case we send an exception, which is slightly more refined than an ANR.
The second part deals more specifically with labels.
Only in the "no rotation" case we computed if the label was visible or not.
That means that in all non-0 rotation cases, we presumed that the label was visible, hence the forever loops.
Now we roughly compute cases when the label is invisible in all rotations. No more forever loops for labels.
=> fix: prevent infinite looping when polygon labels displayed on rotated map

lib/src/layer/tile_layer/tile_coordinates.dart, lib/src/layer/tile_layer/tile_image_manager.dart, lib/src/layer/tile_layer/tile_layer.dart
The fix was to add the concept of `zoomOffset` to `TileCoordinatesResolver`, in order to compute correct modulus.
Fixes: #2042
The world as normal:
The world as simulated retina:
=> fix: consider `zoomOffset` & emulated retina mode when generating tile coordinates

lib/src/layer/attribution_layer/rich/widget.dart, lib/src/layer/attribution_layer/simple.dart
Noticed on Android 15 with the new edge-to-edge mode that the attribution was now hidden below the navigation/gesture bar. This just wraps them with `SafeArea` to push them up.
I've also removed the asymmetric border rounding from the `RichAttributionWidget` because it doesn't look to good on most devices and was making things unnecessarily complex. I wouldn't consider this a breaking fix.
=> fix: raise attribution widgets above screen insets

example/lib/main.dart, example/lib/pages/one_world_or_not.dart, example/lib/pages/repeated_worlds.dart, example/lib/pages/single_world_polys.dart, example/lib/widgets/drawer/menu_drawer.dart, lib/src/geo/crs.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polygon_layer/polygon_layer.dart, lib/src/layer/polygon_layer/projected_polygon.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/polyline_layer/polyline_layer.dart, lib/src/layer/polyline_layer/projected_polyline.dart, lib/src/layer/shared/feature_layer_utils.dart, lib/src/misc/offsets.dart
- We have a new `bool oneWorld` parameter for `PolygonLayer`s and `PolylineLayer`s.
- Default value is `false`.
- If that parameter is `true`, each list of points will be projected in the same (central) world - for instance, -179 and 179 longitudes will be considered almost a world away for 2 consecutive points.
- If that parameter is `false`, each "next" point will be as close as possible to the "previous" point of the list - for instance, -179 and 179 longitudes will be considered very close for 2 consecutive points.
- As it's a parameter at the level of `PolygonLayer`s and `PolylineLayer`s, we can display both "oneWorld" behaviors on the same map (if needed).
- Closes: #2067
Taken from the new "One World - or not - Layers" demo:
New file:
* `one_world_or_not.dart`: Demo of how the new …
=> feat: added `Poly*Layer.drawInSingleWorld`

lib/src/layer/shared/feature_layer_utils.dart
=> fix: make `FeatureLayerUtils.viewportRect` return `Rect.zero` if unavailable

example/lib/pages/polygon.dart, lib/src/geo/latlng_bounds.dart, lib/src/map/camera/camera.dart, test/map/map_controller_test.dart
- This PR introduces the concept of "world safe" latlng bounds: with a north, a south, a longitude center and a longitude width.
- With "world safe" bounds, we can have bounds wider than a world.
- The bounds of the camera are computed as wide as they actually are. Therefore, potentially wider than the world, instead of limited to the currently projected left and right sides of the page.
- A typical use-case is for the camera bounds when we're culling polygons. We now compare polygon bounds with more relevant camera bounds.
- TODO:
- try to refactor so that polygons and polylines share significant parts of the culling algorithm
- try to refactor as there's repeated code about poly continuity, as a list of pixels and as a list of latlngs
- maybe copy/move the concept of "drawInSingleWorld" …
=> fix: consider multi-worlds when constructing camera bounds & allow bounds wider than a world

lib/src/layer/shared/feature_layer_utils.dart
As discussed in https://github.com/fleaflet/flutter_map/issues/2111#issuecomment-2996083734, some fine-tuning about infinite loop error.
=> fix: adjust infinite loop protection in `workAcrossWorlds`

example/lib/pages/polygon.dart, lib/src/layer/polygon_layer/painter.dart, lib/src/layer/polyline_layer/painter.dart, lib/src/layer/shared/feature_layer_utils.dart, lib/src/layer/shared/layer_interactivity/internal_hit_detectable.dart, lib/src/map/camera/camera.dart, lib/src/misc/offsets.dart
Fixes #2092.
Also added `.coordinate` demo to Polygons example.
I also removed `FeatureLayerUtils.origin` in favour of `MapCamera.pixelOrigin`. I'm not 100% if this is correct, but it seems to make sense.
=> fix: calculate `LayerHitResult.coordinate` correctly

example/lib/pages/tile_builder.dart
There was an overflow problems in tile builder demo. 
Another exception was thrown: A RenderFlex overflowed by 37 pixels on the bottom.
The specific RenderFlex in question is: RenderFlex#3b4bf OVERFLOWING:
creator: Column ← Stack ← DecoratedBox ← Positioned ← Tile-[TileRenderer#07efd] ← Stack ← Transform
← OverflowBox ← MobileLayerTransformer ← TileLayer ← ColorFiltered ← Stack ← ⋯
Putting a Column into Fitted box resolves this problem.
=> fix(example): prevent widget overflow in tile builder demo
